// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yeying/api/mcp/resource.proto
// Protobuf Java Version: 4.29.3

package yeying.api.mcp;

public final class ResourceOuterClass {
  private ResourceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ResourceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035yeying/api/mcp/resource.proto\022\016yeying." +
      "api.mcp\032\037yeying/api/common/message.proto" +
      "\032\034yeying/api/common/code.proto2\n\n\010Resour" +
      "ceB\020Z\016yeying/api/mcpb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          yeying.api.common.Message.getDescriptor(),
          yeying.api.common.Code.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    yeying.api.common.Message.getDescriptor();
    yeying.api.common.Code.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
