// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yeying/api/apps/zuoyepigai/imagecontent.proto
// Protobuf Java Version: 4.29.3

package yeying.api.apps.zuoyepigai;

public final class Imagecontent {
  private Imagecontent() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Imagecontent.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * *
   * 图片内容类型
   * </pre>
   *
   * Protobuf enum {@code yeying.api.apps.zuoyepigai.ImageContentTypeEnum}
   */
  public enum ImageContentTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * *
     * 题目
     * </pre>
     *
     * <code>QUESTION = 0;</code>
     */
    QUESTION(0),
    /**
     * <pre>
     * *
     * 答案
     * </pre>
     *
     * <code>ANSWER = 1;</code>
     */
    ANSWER(1),
    /**
     * <pre>
     * *
     * 题目和答案
     * </pre>
     *
     * <code>QA = 2;</code>
     */
    QA(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ImageContentTypeEnum.class.getName());
    }
    /**
     * <pre>
     * *
     * 题目
     * </pre>
     *
     * <code>QUESTION = 0;</code>
     */
    public static final int QUESTION_VALUE = 0;
    /**
     * <pre>
     * *
     * 答案
     * </pre>
     *
     * <code>ANSWER = 1;</code>
     */
    public static final int ANSWER_VALUE = 1;
    /**
     * <pre>
     * *
     * 题目和答案
     * </pre>
     *
     * <code>QA = 2;</code>
     */
    public static final int QA_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ImageContentTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ImageContentTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return QUESTION;
        case 1: return ANSWER;
        case 2: return QA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ImageContentTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ImageContentTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ImageContentTypeEnum>() {
            public ImageContentTypeEnum findValueByNumber(int number) {
              return ImageContentTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.apps.zuoyepigai.Imagecontent.getDescriptor().getEnumTypes().get(0);
    }

    private static final ImageContentTypeEnum[] VALUES = values();

    public static ImageContentTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ImageContentTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.apps.zuoyepigai.ImageContentTypeEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-yeying/api/apps/zuoyepigai/imageconten" +
      "t.proto\022\032yeying.api.apps.zuoyepigai*8\n\024I" +
      "mageContentTypeEnum\022\014\n\010QUESTION\020\000\022\n\n\006ANS" +
      "WER\020\001\022\006\n\002QA\020\002B\034Z\032yeying/api/apps/zuoyepi" +
      "gaib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
