// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/config/config.proto (package yeying.api.config, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageHeader, ResponseStatus } from "../common/message_pb";
import { file_yeying_api_common_message } from "../common/message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/config/config.proto.
 */
export const file_yeying_api_config_config: GenFile = /*@__PURE__*/
  fileDesc("Ch55ZXlpbmcvYXBpL2NvbmZpZy9jb25maWcucHJvdG8SEXlleWluZy5hcGkuY29uZmlnInsKEEdldENvbmZpZ1JlcXVlc3QSMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI1CgRib2R5GAIgASgLMicueWV5aW5nLmFwaS5jb25maWcuR2V0Q29uZmlnUmVxdWVzdEJvZHkiVAoUR2V0Q29uZmlnUmVxdWVzdEJvZHkSCwoDa2V5GAEgASgJEi8KBHR5cGUYAiABKA4yIS55ZXlpbmcuYXBpLmNvbmZpZy5Db25maWdUeXBlRW51bSJ9ChFHZXRDb25maWdSZXNwb25zZRIwCgZoZWFkZXIYASABKAsyIC55ZXlpbmcuYXBpLmNvbW1vbi5NZXNzYWdlSGVhZGVyEjYKBGJvZHkYAiABKAsyKC55ZXlpbmcuYXBpLmNvbmZpZy5HZXRDb25maWdSZXNwb25zZUJvZHkifQoVR2V0Q29uZmlnUmVzcG9uc2VCb2R5EjEKBnN0YXR1cxgBIAEoCzIhLnlleWluZy5hcGkuY29tbW9uLlJlc3BvbnNlU3RhdHVzEjEKBmNvbmZpZxgCIAEoCzIhLnlleWluZy5hcGkuY29uZmlnLkNvbmZpZ01ldGFkYXRhInsKEFNldENvbmZpZ1JlcXVlc3QSMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI1CgRib2R5GAIgASgLMicueWV5aW5nLmFwaS5jb25maWcuU2V0Q29uZmlnUmVxdWVzdEJvZHkiSQoUU2V0Q29uZmlnUmVxdWVzdEJvZHkSMQoGY29uZmlnGAEgASgLMiEueWV5aW5nLmFwaS5jb25maWcuQ29uZmlnTWV0YWRhdGEifQoRU2V0Q29uZmlnUmVzcG9uc2USMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI2CgRib2R5GAIgASgLMigueWV5aW5nLmFwaS5jb25maWcuU2V0Q29uZmlnUmVzcG9uc2VCb2R5In0KFVNldENvbmZpZ1Jlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1cxIxCgZjb25maWcYAiABKAsyIS55ZXlpbmcuYXBpLmNvbmZpZy5Db25maWdNZXRhZGF0YSJ0Cg5Db25maWdNZXRhZGF0YRINCgVvd25lchgBIAEoCRILCgNrZXkYAiABKAkSDQoFdmFsdWUYAyABKAkSEQoJY3JlYXRlZEF0GAQgASgJEhEKCXVwZGF0ZWRBdBgFIAEoCRIRCglzaWduYXR1cmUYBiABKAkqVwoOQ29uZmlnVHlwZUVudW0SFwoTQ09ORklHX1RZUEVfVU5LTk9XThAAEhYKEkNPTkZJR19UWVBFX1NZU1RFTRABEhQKEENPTkZJR19UWVBFX1VTRVIQAjKwAQoGQ29uZmlnElIKA1NldBIjLnlleWluZy5hcGkuY29uZmlnLlNldENvbmZpZ1JlcXVlc3QaJC55ZXlpbmcuYXBpLmNvbmZpZy5TZXRDb25maWdSZXNwb25zZSIAElIKA0dldBIjLnlleWluZy5hcGkuY29uZmlnLkdldENvbmZpZ1JlcXVlc3QaJC55ZXlpbmcuYXBpLmNvbmZpZy5HZXRDb25maWdSZXNwb25zZSIAQhNaEXlleWluZy9hcGkvY29uZmlnYgZwcm90bzM", [file_yeying_api_common_message]);

/**
 * @generated from message yeying.api.config.GetConfigRequest
 */
export type GetConfigRequest = Message<"yeying.api.config.GetConfigRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.config.GetConfigRequestBody body = 2;
   */
  body?: GetConfigRequestBody;
};

/**
 * Describes the message yeying.api.config.GetConfigRequest.
 * Use `create(GetConfigRequestSchema)` to create a new message.
 */
export const GetConfigRequestSchema: GenMessage<GetConfigRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 0);

/**
 * @generated from message yeying.api.config.GetConfigRequestBody
 */
export type GetConfigRequestBody = Message<"yeying.api.config.GetConfigRequestBody"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: yeying.api.config.ConfigTypeEnum type = 2;
   */
  type: ConfigTypeEnum;
};

/**
 * Describes the message yeying.api.config.GetConfigRequestBody.
 * Use `create(GetConfigRequestBodySchema)` to create a new message.
 */
export const GetConfigRequestBodySchema: GenMessage<GetConfigRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 1);

/**
 * @generated from message yeying.api.config.GetConfigResponse
 */
export type GetConfigResponse = Message<"yeying.api.config.GetConfigResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.config.GetConfigResponseBody body = 2;
   */
  body?: GetConfigResponseBody;
};

/**
 * Describes the message yeying.api.config.GetConfigResponse.
 * Use `create(GetConfigResponseSchema)` to create a new message.
 */
export const GetConfigResponseSchema: GenMessage<GetConfigResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 2);

/**
 * @generated from message yeying.api.config.GetConfigResponseBody
 */
export type GetConfigResponseBody = Message<"yeying.api.config.GetConfigResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * @generated from field: yeying.api.config.ConfigMetadata config = 2;
   */
  config?: ConfigMetadata;
};

/**
 * Describes the message yeying.api.config.GetConfigResponseBody.
 * Use `create(GetConfigResponseBodySchema)` to create a new message.
 */
export const GetConfigResponseBodySchema: GenMessage<GetConfigResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 3);

/**
 * @generated from message yeying.api.config.SetConfigRequest
 */
export type SetConfigRequest = Message<"yeying.api.config.SetConfigRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.config.SetConfigRequestBody body = 2;
   */
  body?: SetConfigRequestBody;
};

/**
 * Describes the message yeying.api.config.SetConfigRequest.
 * Use `create(SetConfigRequestSchema)` to create a new message.
 */
export const SetConfigRequestSchema: GenMessage<SetConfigRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 4);

/**
 * @generated from message yeying.api.config.SetConfigRequestBody
 */
export type SetConfigRequestBody = Message<"yeying.api.config.SetConfigRequestBody"> & {
  /**
   * @generated from field: yeying.api.config.ConfigMetadata config = 1;
   */
  config?: ConfigMetadata;
};

/**
 * Describes the message yeying.api.config.SetConfigRequestBody.
 * Use `create(SetConfigRequestBodySchema)` to create a new message.
 */
export const SetConfigRequestBodySchema: GenMessage<SetConfigRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 5);

/**
 * @generated from message yeying.api.config.SetConfigResponse
 */
export type SetConfigResponse = Message<"yeying.api.config.SetConfigResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.config.SetConfigResponseBody body = 2;
   */
  body?: SetConfigResponseBody;
};

/**
 * Describes the message yeying.api.config.SetConfigResponse.
 * Use `create(SetConfigResponseSchema)` to create a new message.
 */
export const SetConfigResponseSchema: GenMessage<SetConfigResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 6);

/**
 * @generated from message yeying.api.config.SetConfigResponseBody
 */
export type SetConfigResponseBody = Message<"yeying.api.config.SetConfigResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * @generated from field: yeying.api.config.ConfigMetadata config = 2;
   */
  config?: ConfigMetadata;
};

/**
 * Describes the message yeying.api.config.SetConfigResponseBody.
 * Use `create(SetConfigResponseBodySchema)` to create a new message.
 */
export const SetConfigResponseBodySchema: GenMessage<SetConfigResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 7);

/**
 * @generated from message yeying.api.config.ConfigMetadata
 */
export type ConfigMetadata = Message<"yeying.api.config.ConfigMetadata"> & {
  /**
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * @generated from field: string key = 2;
   */
  key: string;

  /**
   * @generated from field: string value = 3;
   */
  value: string;

  /**
   * @generated from field: string createdAt = 4;
   */
  createdAt: string;

  /**
   * @generated from field: string updatedAt = 5;
   */
  updatedAt: string;

  /**
   * @generated from field: string signature = 6;
   */
  signature: string;
};

/**
 * Describes the message yeying.api.config.ConfigMetadata.
 * Use `create(ConfigMetadataSchema)` to create a new message.
 */
export const ConfigMetadataSchema: GenMessage<ConfigMetadata> = /*@__PURE__*/
  messageDesc(file_yeying_api_config_config, 8);

/**
 * @generated from enum yeying.api.config.ConfigTypeEnum
 */
export enum ConfigTypeEnum {
  /**
   * 未知编码，是一种占位符
   *
   * @generated from enum value: CONFIG_TYPE_UNKNOWN = 0;
   */
  CONFIG_TYPE_UNKNOWN = 0,

  /**
   * 系统配置
   *
   * @generated from enum value: CONFIG_TYPE_SYSTEM = 1;
   */
  CONFIG_TYPE_SYSTEM = 1,

  /**
   * 用户配置
   *
   * @generated from enum value: CONFIG_TYPE_USER = 2;
   */
  CONFIG_TYPE_USER = 2,
}

/**
 * Describes the enum yeying.api.config.ConfigTypeEnum.
 */
export const ConfigTypeEnumSchema: GenEnum<ConfigTypeEnum> = /*@__PURE__*/
  enumDesc(file_yeying_api_config_config, 0);

/**
 * @generated from service yeying.api.config.Config
 */
export const Config: GenService<{
  /**
   * @generated from rpc yeying.api.config.Config.Set
   */
  set: {
    methodKind: "unary";
    input: typeof SetConfigRequestSchema;
    output: typeof SetConfigResponseSchema;
  },
  /**
   * @generated from rpc yeying.api.config.Config.Get
   */
  get: {
    methodKind: "unary";
    input: typeof GetConfigRequestSchema;
    output: typeof GetConfigResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yeying_api_config_config, 0);

