// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/bulletin/bulletin.proto (package yeying.api.bulletin, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageHeader, RequestPage, ResponsePage, ResponseStatus } from "../common/message_pb";
import { file_yeying_api_common_message } from "../common/message_pb";
import type { LanguageCodeEnum } from "../common/code_pb";
import { file_yeying_api_common_code } from "../common/code_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/bulletin/bulletin.proto.
 */
export const file_yeying_api_bulletin_bulletin: GenFile = /*@__PURE__*/
  fileDesc("CiJ5ZXlpbmcvYXBpL2J1bGxldGluL2J1bGxldGluLnByb3RvEhN5ZXlpbmcuYXBpLmJ1bGxldGluIoMBChNCdWxsZXRpbkxpc3RSZXF1ZXN0EjAKBmhlYWRlchgBIAEoCzIgLnlleWluZy5hcGkuY29tbW9uLk1lc3NhZ2VIZWFkZXISOgoEYm9keRgCIAEoCzIsLnlleWluZy5hcGkuYnVsbGV0aW4uQnVsbGV0aW5MaXN0UmVxdWVzdEJvZHkiswEKF0J1bGxldGluTGlzdFJlcXVlc3RCb2R5EjMKBGNvZGUYASABKA4yJS55ZXlpbmcuYXBpLmJ1bGxldGluLkJ1bGxldGluQ29kZUVudW0SNQoIbGFuZ3VhZ2UYAiABKA4yIy55ZXlpbmcuYXBpLmNvbW1vbi5MYW5ndWFnZUNvZGVFbnVtEiwKBHBhZ2UYAyABKAsyHi55ZXlpbmcuYXBpLmNvbW1vbi5SZXF1ZXN0UGFnZSKFAQoUQnVsbGV0aW5MaXN0UmVzcG9uc2USMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI7CgRib2R5GAIgASgLMi0ueWV5aW5nLmFwaS5idWxsZXRpbi5CdWxsZXRpbkxpc3RSZXNwb25zZUJvZHkitgEKGEJ1bGxldGluTGlzdFJlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1cxI4Cglzb2x1dGlvbnMYAiADKAsyJS55ZXlpbmcuYXBpLmJ1bGxldGluLlNvbHV0aW9uTWV0YWRhdGESLQoEcGFnZRgDIAEoCzIfLnlleWluZy5hcGkuY29tbW9uLlJlc3BvbnNlUGFnZSLkAQoQU29sdXRpb25NZXRhZGF0YRIRCglwdWJsaXNoZXIYASABKAkSNQoIbGFuZ3VhZ2UYAiABKA4yIy55ZXlpbmcuYXBpLmNvbW1vbi5MYW5ndWFnZUNvZGVFbnVtEgsKA3VpZBgDIAEoCRIMCgRuYW1lGAQgASgJEhMKC2Rlc2NyaXB0aW9uGAUgASgJEhEKCWNyZWF0ZWRBdBgGIAEoCRIwCgVjYXJkcxgHIAMoCzIhLnlleWluZy5hcGkuYnVsbGV0aW4uU29sdXRpb25DYXJkEhEKCXNpZ25hdHVyZRgIIAEoCSI+CgxTb2x1dGlvbkNhcmQSDAoEbmFtZRgBIAEoCRINCgVwcmljZRgCIAEoCRIRCgl2YXJpYWJsZXMYAyABKAkqLgoQQnVsbGV0aW5Db2RlRW51bRIaChZCVUxMRVRJTl9DT0RFX1NPTFVUSU9OEAAyaQoIQnVsbGV0aW4SXQoETGlzdBIoLnlleWluZy5hcGkuYnVsbGV0aW4uQnVsbGV0aW5MaXN0UmVxdWVzdBopLnlleWluZy5hcGkuYnVsbGV0aW4uQnVsbGV0aW5MaXN0UmVzcG9uc2UiAEIVWhN5ZXlpbmcvYXBpL2J1bGxldGluYgZwcm90bzM", [file_yeying_api_common_message, file_yeying_api_common_code]);

/**
 * @generated from message yeying.api.bulletin.BulletinListRequest
 */
export type BulletinListRequest = Message<"yeying.api.bulletin.BulletinListRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.bulletin.BulletinListRequestBody body = 2;
   */
  body?: BulletinListRequestBody;
};

/**
 * Describes the message yeying.api.bulletin.BulletinListRequest.
 * Use `create(BulletinListRequestSchema)` to create a new message.
 */
export const BulletinListRequestSchema: GenMessage<BulletinListRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_bulletin_bulletin, 0);

/**
 * @generated from message yeying.api.bulletin.BulletinListRequestBody
 */
export type BulletinListRequestBody = Message<"yeying.api.bulletin.BulletinListRequestBody"> & {
  /**
   * @generated from field: yeying.api.bulletin.BulletinCodeEnum code = 1;
   */
  code: BulletinCodeEnum;

  /**
   * @generated from field: yeying.api.common.LanguageCodeEnum language = 2;
   */
  language: LanguageCodeEnum;

  /**
   * @generated from field: yeying.api.common.RequestPage page = 3;
   */
  page?: RequestPage;
};

/**
 * Describes the message yeying.api.bulletin.BulletinListRequestBody.
 * Use `create(BulletinListRequestBodySchema)` to create a new message.
 */
export const BulletinListRequestBodySchema: GenMessage<BulletinListRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_bulletin_bulletin, 1);

/**
 * @generated from message yeying.api.bulletin.BulletinListResponse
 */
export type BulletinListResponse = Message<"yeying.api.bulletin.BulletinListResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.bulletin.BulletinListResponseBody body = 2;
   */
  body?: BulletinListResponseBody;
};

/**
 * Describes the message yeying.api.bulletin.BulletinListResponse.
 * Use `create(BulletinListResponseSchema)` to create a new message.
 */
export const BulletinListResponseSchema: GenMessage<BulletinListResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_bulletin_bulletin, 2);

/**
 * @generated from message yeying.api.bulletin.BulletinListResponseBody
 */
export type BulletinListResponseBody = Message<"yeying.api.bulletin.BulletinListResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;

  /**
   * @generated from field: repeated yeying.api.bulletin.SolutionMetadata solutions = 2;
   */
  solutions: SolutionMetadata[];

  /**
   * @generated from field: yeying.api.common.ResponsePage page = 3;
   */
  page?: ResponsePage;
};

/**
 * Describes the message yeying.api.bulletin.BulletinListResponseBody.
 * Use `create(BulletinListResponseBodySchema)` to create a new message.
 */
export const BulletinListResponseBodySchema: GenMessage<BulletinListResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_bulletin_bulletin, 3);

/**
 * @generated from message yeying.api.bulletin.SolutionMetadata
 */
export type SolutionMetadata = Message<"yeying.api.bulletin.SolutionMetadata"> & {
  /**
   * @generated from field: string publisher = 1;
   */
  publisher: string;

  /**
   * @generated from field: yeying.api.common.LanguageCodeEnum language = 2;
   */
  language: LanguageCodeEnum;

  /**
   * @generated from field: string uid = 3;
   */
  uid: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * @generated from field: string createdAt = 6;
   */
  createdAt: string;

  /**
   * @generated from field: repeated yeying.api.bulletin.SolutionCard cards = 7;
   */
  cards: SolutionCard[];

  /**
   * @generated from field: string signature = 8;
   */
  signature: string;
};

/**
 * Describes the message yeying.api.bulletin.SolutionMetadata.
 * Use `create(SolutionMetadataSchema)` to create a new message.
 */
export const SolutionMetadataSchema: GenMessage<SolutionMetadata> = /*@__PURE__*/
  messageDesc(file_yeying_api_bulletin_bulletin, 4);

/**
 * @generated from message yeying.api.bulletin.SolutionCard
 */
export type SolutionCard = Message<"yeying.api.bulletin.SolutionCard"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string price = 2;
   */
  price: string;

  /**
   * @generated from field: string variables = 3;
   */
  variables: string;
};

/**
 * Describes the message yeying.api.bulletin.SolutionCard.
 * Use `create(SolutionCardSchema)` to create a new message.
 */
export const SolutionCardSchema: GenMessage<SolutionCard> = /*@__PURE__*/
  messageDesc(file_yeying_api_bulletin_bulletin, 5);

/**
 * @generated from enum yeying.api.bulletin.BulletinCodeEnum
 */
export enum BulletinCodeEnum {
  /**
   * @generated from enum value: BULLETIN_CODE_SOLUTION = 0;
   */
  BULLETIN_CODE_SOLUTION = 0,
}

/**
 * Describes the enum yeying.api.bulletin.BulletinCodeEnum.
 */
export const BulletinCodeEnumSchema: GenEnum<BulletinCodeEnum> = /*@__PURE__*/
  enumDesc(file_yeying_api_bulletin_bulletin, 0);

/**
 * @generated from service yeying.api.bulletin.Bulletin
 */
export const Bulletin: GenService<{
  /**
   * @generated from rpc yeying.api.bulletin.Bulletin.List
   */
  list: {
    methodKind: "unary";
    input: typeof BulletinListRequestSchema;
    output: typeof BulletinListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yeying_api_bulletin_bulletin, 0);

