// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yeying/api/social/social.proto
// Protobuf Java Version: 4.29.3

package yeying.api.social;

public final class SocialOuterClass {
  private SocialOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      SocialOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MakeFriendsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yeying.api.social.MakeFriendsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code yeying.api.social.MakeFriendsRequest}
   */
  public static final class MakeFriendsRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:yeying.api.social.MakeFriendsRequest)
      MakeFriendsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MakeFriendsRequest.class.getName());
    }
    // Use MakeFriendsRequest.newBuilder() to construct.
    private MakeFriendsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MakeFriendsRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yeying.api.social.SocialOuterClass.MakeFriendsRequest.class, yeying.api.social.SocialOuterClass.MakeFriendsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yeying.api.social.SocialOuterClass.MakeFriendsRequest)) {
        return super.equals(obj);
      }
      yeying.api.social.SocialOuterClass.MakeFriendsRequest other = (yeying.api.social.SocialOuterClass.MakeFriendsRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yeying.api.social.SocialOuterClass.MakeFriendsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code yeying.api.social.MakeFriendsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yeying.api.social.MakeFriendsRequest)
        yeying.api.social.SocialOuterClass.MakeFriendsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yeying.api.social.SocialOuterClass.MakeFriendsRequest.class, yeying.api.social.SocialOuterClass.MakeFriendsRequest.Builder.class);
      }

      // Construct using yeying.api.social.SocialOuterClass.MakeFriendsRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsRequest_descriptor;
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.MakeFriendsRequest getDefaultInstanceForType() {
        return yeying.api.social.SocialOuterClass.MakeFriendsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.MakeFriendsRequest build() {
        yeying.api.social.SocialOuterClass.MakeFriendsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.MakeFriendsRequest buildPartial() {
        yeying.api.social.SocialOuterClass.MakeFriendsRequest result = new yeying.api.social.SocialOuterClass.MakeFriendsRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yeying.api.social.SocialOuterClass.MakeFriendsRequest) {
          return mergeFrom((yeying.api.social.SocialOuterClass.MakeFriendsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yeying.api.social.SocialOuterClass.MakeFriendsRequest other) {
        if (other == yeying.api.social.SocialOuterClass.MakeFriendsRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:yeying.api.social.MakeFriendsRequest)
    }

    // @@protoc_insertion_point(class_scope:yeying.api.social.MakeFriendsRequest)
    private static final yeying.api.social.SocialOuterClass.MakeFriendsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yeying.api.social.SocialOuterClass.MakeFriendsRequest();
    }

    public static yeying.api.social.SocialOuterClass.MakeFriendsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MakeFriendsRequest>
        PARSER = new com.google.protobuf.AbstractParser<MakeFriendsRequest>() {
      @java.lang.Override
      public MakeFriendsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MakeFriendsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MakeFriendsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yeying.api.social.SocialOuterClass.MakeFriendsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MakeFriendsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yeying.api.social.MakeFriendsResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code yeying.api.social.MakeFriendsResponse}
   */
  public static final class MakeFriendsResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:yeying.api.social.MakeFriendsResponse)
      MakeFriendsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MakeFriendsResponse.class.getName());
    }
    // Use MakeFriendsResponse.newBuilder() to construct.
    private MakeFriendsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MakeFriendsResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yeying.api.social.SocialOuterClass.MakeFriendsResponse.class, yeying.api.social.SocialOuterClass.MakeFriendsResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yeying.api.social.SocialOuterClass.MakeFriendsResponse)) {
        return super.equals(obj);
      }
      yeying.api.social.SocialOuterClass.MakeFriendsResponse other = (yeying.api.social.SocialOuterClass.MakeFriendsResponse) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yeying.api.social.SocialOuterClass.MakeFriendsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code yeying.api.social.MakeFriendsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yeying.api.social.MakeFriendsResponse)
        yeying.api.social.SocialOuterClass.MakeFriendsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yeying.api.social.SocialOuterClass.MakeFriendsResponse.class, yeying.api.social.SocialOuterClass.MakeFriendsResponse.Builder.class);
      }

      // Construct using yeying.api.social.SocialOuterClass.MakeFriendsResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_MakeFriendsResponse_descriptor;
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.MakeFriendsResponse getDefaultInstanceForType() {
        return yeying.api.social.SocialOuterClass.MakeFriendsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.MakeFriendsResponse build() {
        yeying.api.social.SocialOuterClass.MakeFriendsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.MakeFriendsResponse buildPartial() {
        yeying.api.social.SocialOuterClass.MakeFriendsResponse result = new yeying.api.social.SocialOuterClass.MakeFriendsResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yeying.api.social.SocialOuterClass.MakeFriendsResponse) {
          return mergeFrom((yeying.api.social.SocialOuterClass.MakeFriendsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yeying.api.social.SocialOuterClass.MakeFriendsResponse other) {
        if (other == yeying.api.social.SocialOuterClass.MakeFriendsResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:yeying.api.social.MakeFriendsResponse)
    }

    // @@protoc_insertion_point(class_scope:yeying.api.social.MakeFriendsResponse)
    private static final yeying.api.social.SocialOuterClass.MakeFriendsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yeying.api.social.SocialOuterClass.MakeFriendsResponse();
    }

    public static yeying.api.social.SocialOuterClass.MakeFriendsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MakeFriendsResponse>
        PARSER = new com.google.protobuf.AbstractParser<MakeFriendsResponse>() {
      @java.lang.Override
      public MakeFriendsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MakeFriendsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MakeFriendsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yeying.api.social.SocialOuterClass.MakeFriendsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetFriendsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yeying.api.social.GetFriendsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code yeying.api.social.GetFriendsRequest}
   */
  public static final class GetFriendsRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:yeying.api.social.GetFriendsRequest)
      GetFriendsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        GetFriendsRequest.class.getName());
    }
    // Use GetFriendsRequest.newBuilder() to construct.
    private GetFriendsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetFriendsRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yeying.api.social.SocialOuterClass.GetFriendsRequest.class, yeying.api.social.SocialOuterClass.GetFriendsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yeying.api.social.SocialOuterClass.GetFriendsRequest)) {
        return super.equals(obj);
      }
      yeying.api.social.SocialOuterClass.GetFriendsRequest other = (yeying.api.social.SocialOuterClass.GetFriendsRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yeying.api.social.SocialOuterClass.GetFriendsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code yeying.api.social.GetFriendsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yeying.api.social.GetFriendsRequest)
        yeying.api.social.SocialOuterClass.GetFriendsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yeying.api.social.SocialOuterClass.GetFriendsRequest.class, yeying.api.social.SocialOuterClass.GetFriendsRequest.Builder.class);
      }

      // Construct using yeying.api.social.SocialOuterClass.GetFriendsRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendsRequest_descriptor;
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.GetFriendsRequest getDefaultInstanceForType() {
        return yeying.api.social.SocialOuterClass.GetFriendsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.GetFriendsRequest build() {
        yeying.api.social.SocialOuterClass.GetFriendsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.GetFriendsRequest buildPartial() {
        yeying.api.social.SocialOuterClass.GetFriendsRequest result = new yeying.api.social.SocialOuterClass.GetFriendsRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yeying.api.social.SocialOuterClass.GetFriendsRequest) {
          return mergeFrom((yeying.api.social.SocialOuterClass.GetFriendsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yeying.api.social.SocialOuterClass.GetFriendsRequest other) {
        if (other == yeying.api.social.SocialOuterClass.GetFriendsRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:yeying.api.social.GetFriendsRequest)
    }

    // @@protoc_insertion_point(class_scope:yeying.api.social.GetFriendsRequest)
    private static final yeying.api.social.SocialOuterClass.GetFriendsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yeying.api.social.SocialOuterClass.GetFriendsRequest();
    }

    public static yeying.api.social.SocialOuterClass.GetFriendsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetFriendsRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetFriendsRequest>() {
      @java.lang.Override
      public GetFriendsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetFriendsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFriendsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yeying.api.social.SocialOuterClass.GetFriendsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetFriendResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yeying.api.social.GetFriendResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code yeying.api.social.GetFriendResponse}
   */
  public static final class GetFriendResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:yeying.api.social.GetFriendResponse)
      GetFriendResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        GetFriendResponse.class.getName());
    }
    // Use GetFriendResponse.newBuilder() to construct.
    private GetFriendResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetFriendResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yeying.api.social.SocialOuterClass.GetFriendResponse.class, yeying.api.social.SocialOuterClass.GetFriendResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof yeying.api.social.SocialOuterClass.GetFriendResponse)) {
        return super.equals(obj);
      }
      yeying.api.social.SocialOuterClass.GetFriendResponse other = (yeying.api.social.SocialOuterClass.GetFriendResponse) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static yeying.api.social.SocialOuterClass.GetFriendResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(yeying.api.social.SocialOuterClass.GetFriendResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code yeying.api.social.GetFriendResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yeying.api.social.GetFriendResponse)
        yeying.api.social.SocialOuterClass.GetFriendResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yeying.api.social.SocialOuterClass.GetFriendResponse.class, yeying.api.social.SocialOuterClass.GetFriendResponse.Builder.class);
      }

      // Construct using yeying.api.social.SocialOuterClass.GetFriendResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yeying.api.social.SocialOuterClass.internal_static_yeying_api_social_GetFriendResponse_descriptor;
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.GetFriendResponse getDefaultInstanceForType() {
        return yeying.api.social.SocialOuterClass.GetFriendResponse.getDefaultInstance();
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.GetFriendResponse build() {
        yeying.api.social.SocialOuterClass.GetFriendResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public yeying.api.social.SocialOuterClass.GetFriendResponse buildPartial() {
        yeying.api.social.SocialOuterClass.GetFriendResponse result = new yeying.api.social.SocialOuterClass.GetFriendResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yeying.api.social.SocialOuterClass.GetFriendResponse) {
          return mergeFrom((yeying.api.social.SocialOuterClass.GetFriendResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yeying.api.social.SocialOuterClass.GetFriendResponse other) {
        if (other == yeying.api.social.SocialOuterClass.GetFriendResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:yeying.api.social.GetFriendResponse)
    }

    // @@protoc_insertion_point(class_scope:yeying.api.social.GetFriendResponse)
    private static final yeying.api.social.SocialOuterClass.GetFriendResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new yeying.api.social.SocialOuterClass.GetFriendResponse();
    }

    public static yeying.api.social.SocialOuterClass.GetFriendResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetFriendResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetFriendResponse>() {
      @java.lang.Override
      public GetFriendResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetFriendResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFriendResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public yeying.api.social.SocialOuterClass.GetFriendResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yeying_api_social_MakeFriendsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yeying_api_social_MakeFriendsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yeying_api_social_MakeFriendsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yeying_api_social_MakeFriendsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yeying_api_social_GetFriendsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yeying_api_social_GetFriendsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yeying_api_social_GetFriendResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yeying_api_social_GetFriendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036yeying/api/social/social.proto\022\021yeying" +
      ".api.social\032\037yeying/api/common/message.p" +
      "roto\"\024\n\022MakeFriendsRequest\"\025\n\023MakeFriend" +
      "sResponse\"\023\n\021GetFriendsRequest\"\023\n\021GetFri" +
      "endResponse2\304\001\n\006Social\022^\n\013MakeFriends\022%." +
      "yeying.api.social.MakeFriendsRequest\032&.y" +
      "eying.api.social.MakeFriendsResponse\"\000\022Z" +
      "\n\nGetFriends\022$.yeying.api.social.GetFrie" +
      "ndsRequest\032$.yeying.api.social.GetFriend" +
      "Response\"\000B\023Z\021yeying/api/socialb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          yeying.api.common.Message.getDescriptor(),
        });
    internal_static_yeying_api_social_MakeFriendsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yeying_api_social_MakeFriendsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yeying_api_social_MakeFriendsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_yeying_api_social_MakeFriendsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yeying_api_social_MakeFriendsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yeying_api_social_MakeFriendsResponse_descriptor,
        new java.lang.String[] { });
    internal_static_yeying_api_social_GetFriendsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_yeying_api_social_GetFriendsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yeying_api_social_GetFriendsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_yeying_api_social_GetFriendResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_yeying_api_social_GetFriendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yeying_api_social_GetFriendResponse_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    yeying.api.common.Message.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
