// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/support/support.proto (package yeying.api.support, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageHeader, ResponseStatus } from "../common/message_pb";
import { file_yeying_api_common_message } from "../common/message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/support/support.proto.
 */
export const file_yeying_api_support_support: GenFile = /*@__PURE__*/
  fileDesc("CiB5ZXlpbmcvYXBpL3N1cHBvcnQvc3VwcG9ydC5wcm90bxISeWV5aW5nLmFwaS5zdXBwb3J0IoYBChVDb2xsZWN0U3VwcG9ydFJlcXVlc3QSMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI7CgRib2R5GAIgASgLMi0ueWV5aW5nLmFwaS5zdXBwb3J0LkNvbGxlY3RTdXBwb3J0UmVxdWVzdEJvZHkihgEKGUNvbGxlY3RTdXBwb3J0UmVxdWVzdEJvZHkSMQoEY29kZRgBIAEoDjIjLnlleWluZy5hcGkuc3VwcG9ydC5TdXBwb3J0Q29kZUVudW0SLgoDZmFxGAMgASgLMh8ueWV5aW5nLmFwaS5zdXBwb3J0LkZhcU1ldGFkYXRhSABCBgoEZGF0YSJyCgtGYXFNZXRhZGF0YRILCgNkaWQYASABKAkSDQoFZW1haWwYAiABKAkSDAoEdHlwZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRIRCgljcmVhdGVkQXQYBSABKAkSEQoJc2lnbmF0dXJlGAYgASgJIogBChZDb2xsZWN0U3VwcG9ydFJlc3BvbnNlEjAKBmhlYWRlchgBIAEoCzIgLnlleWluZy5hcGkuY29tbW9uLk1lc3NhZ2VIZWFkZXISPAoEYm9keRgCIAEoCzIuLnlleWluZy5hcGkuc3VwcG9ydC5Db2xsZWN0U3VwcG9ydFJlc3BvbnNlQm9keSJPChpDb2xsZWN0U3VwcG9ydFJlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1cypTCg9TdXBwb3J0Q29kZUVudW0SFAoQU1VQUE9SVF9DT0RFX0ZBURAAEhQKEFNVUFBPUlRfQ09ERV9DU1IQARIUChBTVVBQT1JUX0NPREVfSVZSEAIybQoHU3VwcG9ydBJiCgdDb2xsZWN0EikueWV5aW5nLmFwaS5zdXBwb3J0LkNvbGxlY3RTdXBwb3J0UmVxdWVzdBoqLnlleWluZy5hcGkuc3VwcG9ydC5Db2xsZWN0U3VwcG9ydFJlc3BvbnNlIgBCFFoSeWV5aW5nL2FwaS9zdXBwb3J0YgZwcm90bzM", [file_yeying_api_common_message]);

/**
 * @generated from message yeying.api.support.CollectSupportRequest
 */
export type CollectSupportRequest = Message<"yeying.api.support.CollectSupportRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.support.CollectSupportRequestBody body = 2;
   */
  body?: CollectSupportRequestBody;
};

/**
 * Describes the message yeying.api.support.CollectSupportRequest.
 * Use `create(CollectSupportRequestSchema)` to create a new message.
 */
export const CollectSupportRequestSchema: GenMessage<CollectSupportRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_support_support, 0);

/**
 * @generated from message yeying.api.support.CollectSupportRequestBody
 */
export type CollectSupportRequestBody = Message<"yeying.api.support.CollectSupportRequestBody"> & {
  /**
   * @generated from field: yeying.api.support.SupportCodeEnum code = 1;
   */
  code: SupportCodeEnum;

  /**
   * @generated from oneof yeying.api.support.CollectSupportRequestBody.data
   */
  data: {
    /**
     * @generated from field: yeying.api.support.FaqMetadata faq = 3;
     */
    value: FaqMetadata;
    case: "faq";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message yeying.api.support.CollectSupportRequestBody.
 * Use `create(CollectSupportRequestBodySchema)` to create a new message.
 */
export const CollectSupportRequestBodySchema: GenMessage<CollectSupportRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_support_support, 1);

/**
 * @generated from message yeying.api.support.FaqMetadata
 */
export type FaqMetadata = Message<"yeying.api.support.FaqMetadata"> & {
  /**
   * @generated from field: string did = 1;
   */
  did: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: string createdAt = 5;
   */
  createdAt: string;

  /**
   * @generated from field: string signature = 6;
   */
  signature: string;
};

/**
 * Describes the message yeying.api.support.FaqMetadata.
 * Use `create(FaqMetadataSchema)` to create a new message.
 */
export const FaqMetadataSchema: GenMessage<FaqMetadata> = /*@__PURE__*/
  messageDesc(file_yeying_api_support_support, 2);

/**
 * @generated from message yeying.api.support.CollectSupportResponse
 */
export type CollectSupportResponse = Message<"yeying.api.support.CollectSupportResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.support.CollectSupportResponseBody body = 2;
   */
  body?: CollectSupportResponseBody;
};

/**
 * Describes the message yeying.api.support.CollectSupportResponse.
 * Use `create(CollectSupportResponseSchema)` to create a new message.
 */
export const CollectSupportResponseSchema: GenMessage<CollectSupportResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_support_support, 3);

/**
 * @generated from message yeying.api.support.CollectSupportResponseBody
 */
export type CollectSupportResponseBody = Message<"yeying.api.support.CollectSupportResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;
};

/**
 * Describes the message yeying.api.support.CollectSupportResponseBody.
 * Use `create(CollectSupportResponseBodySchema)` to create a new message.
 */
export const CollectSupportResponseBodySchema: GenMessage<CollectSupportResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_support_support, 4);

/**
 * @generated from enum yeying.api.support.SupportCodeEnum
 */
export enum SupportCodeEnum {
  /**
   * Frequently Asked Questions, 通常包含了最常见的问题以及相应的解答，帮助客户快速找到答案
   *
   * @generated from enum value: SUPPORT_CODE_FAQ = 0;
   */
  SUPPORT_CODE_FAQ = 0,

  /**
   * Customer Service Representative, 通过电话、电子邮件、在线聊天等方式与客户进行沟通，并解决客户的问题和需求
   *
   * @generated from enum value: SUPPORT_CODE_CSR = 1;
   */
  SUPPORT_CODE_CSR = 1,

  /**
   * Interactive Voice Response, 使用预先录制的语音和语音识别技术，引导客户通过按键选择或语音输入，实现自助查询、转接、留言等功能，提高客户体验
   *
   * @generated from enum value: SUPPORT_CODE_IVR = 2;
   */
  SUPPORT_CODE_IVR = 2,
}

/**
 * Describes the enum yeying.api.support.SupportCodeEnum.
 */
export const SupportCodeEnumSchema: GenEnum<SupportCodeEnum> = /*@__PURE__*/
  enumDesc(file_yeying_api_support_support, 0);

/**
 * @generated from service yeying.api.support.Support
 */
export const Support: GenService<{
  /**
   * @generated from rpc yeying.api.support.Support.Collect
   */
  collect: {
    methodKind: "unary";
    input: typeof CollectSupportRequestSchema;
    output: typeof CollectSupportResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yeying_api_support_support, 0);

