// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file yeying/api/mail/mail.proto (package yeying.api.mail, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageHeader, ResponseStatus } from "../common/message_pb";
import { file_yeying_api_common_message } from "../common/message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yeying/api/mail/mail.proto.
 */
export const file_yeying_api_mail_mail: GenFile = /*@__PURE__*/
  fileDesc("Chp5ZXlpbmcvYXBpL21haWwvbWFpbC5wcm90bxIPeWV5aW5nLmFwaS5tYWlsIncKD1NlbmRNYWlsUmVxdWVzdBIwCgZoZWFkZXIYASABKAsyIC55ZXlpbmcuYXBpLmNvbW1vbi5NZXNzYWdlSGVhZGVyEjIKBGJvZHkYAiABKAsyJC55ZXlpbmcuYXBpLm1haWwuU2VuZE1haWxSZXF1ZXN0Qm9keSIlChNTZW5kTWFpbFJlcXVlc3RCb2R5Eg4KBnRvTWFpbBgBIAEoCSJ5ChBTZW5kTWFpbFJlc3BvbnNlEjAKBmhlYWRlchgBIAEoCzIgLnlleWluZy5hcGkuY29tbW9uLk1lc3NhZ2VIZWFkZXISMwoEYm9keRgCIAEoCzIlLnlleWluZy5hcGkubWFpbC5TZW5kTWFpbFJlc3BvbnNlQm9keSJJChRTZW5kTWFpbFJlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1cyJ7ChFWZXJpZnlNYWlsUmVxdWVzdBIwCgZoZWFkZXIYASABKAsyIC55ZXlpbmcuYXBpLmNvbW1vbi5NZXNzYWdlSGVhZGVyEjQKBGJvZHkYAiABKAsyJi55ZXlpbmcuYXBpLm1haWwuVmVyaWZ5TWFpbFJlcXVlc3RCb2R5IjUKFVZlcmlmeU1haWxSZXF1ZXN0Qm9keRIOCgZ0b01haWwYASABKAkSDAoEY29kZRgCIAEoCSJ9ChJWZXJpZnlNYWlsUmVzcG9uc2USMAoGaGVhZGVyGAEgASgLMiAueWV5aW5nLmFwaS5jb21tb24uTWVzc2FnZUhlYWRlchI1CgRib2R5GAIgASgLMicueWV5aW5nLmFwaS5tYWlsLlZlcmlmeU1haWxSZXNwb25zZUJvZHkiSwoWVmVyaWZ5TWFpbFJlc3BvbnNlQm9keRIxCgZzdGF0dXMYASABKAsyIS55ZXlpbmcuYXBpLmNvbW1vbi5SZXNwb25zZVN0YXR1czKqAQoETWFpbBJNCgRTZW5kEiAueWV5aW5nLmFwaS5tYWlsLlNlbmRNYWlsUmVxdWVzdBohLnlleWluZy5hcGkubWFpbC5TZW5kTWFpbFJlc3BvbnNlIgASUwoGVmVyaWZ5EiIueWV5aW5nLmFwaS5tYWlsLlZlcmlmeU1haWxSZXF1ZXN0GiMueWV5aW5nLmFwaS5tYWlsLlZlcmlmeU1haWxSZXNwb25zZSIAQhFaD3lleWluZy9hcGkvbWFpbGIGcHJvdG8z", [file_yeying_api_common_message]);

/**
 * *
 * 邮件请求
 *
 * @generated from message yeying.api.mail.SendMailRequest
 */
export type SendMailRequest = Message<"yeying.api.mail.SendMailRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.mail.SendMailRequestBody body = 2;
   */
  body?: SendMailRequestBody;
};

/**
 * Describes the message yeying.api.mail.SendMailRequest.
 * Use `create(SendMailRequestSchema)` to create a new message.
 */
export const SendMailRequestSchema: GenMessage<SendMailRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_mail_mail, 0);

/**
 * @generated from message yeying.api.mail.SendMailRequestBody
 */
export type SendMailRequestBody = Message<"yeying.api.mail.SendMailRequestBody"> & {
  /**
   * 收件箱
   *
   * @generated from field: string toMail = 1;
   */
  toMail: string;
};

/**
 * Describes the message yeying.api.mail.SendMailRequestBody.
 * Use `create(SendMailRequestBodySchema)` to create a new message.
 */
export const SendMailRequestBodySchema: GenMessage<SendMailRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_mail_mail, 1);

/**
 * *
 * 邮件相应
 *
 * @generated from message yeying.api.mail.SendMailResponse
 */
export type SendMailResponse = Message<"yeying.api.mail.SendMailResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.mail.SendMailResponseBody body = 2;
   */
  body?: SendMailResponseBody;
};

/**
 * Describes the message yeying.api.mail.SendMailResponse.
 * Use `create(SendMailResponseSchema)` to create a new message.
 */
export const SendMailResponseSchema: GenMessage<SendMailResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_mail_mail, 2);

/**
 * @generated from message yeying.api.mail.SendMailResponseBody
 */
export type SendMailResponseBody = Message<"yeying.api.mail.SendMailResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;
};

/**
 * Describes the message yeying.api.mail.SendMailResponseBody.
 * Use `create(SendMailResponseBodySchema)` to create a new message.
 */
export const SendMailResponseBodySchema: GenMessage<SendMailResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_mail_mail, 3);

/**
 * *
 * 验证码验证请求体
 *
 * @generated from message yeying.api.mail.VerifyMailRequest
 */
export type VerifyMailRequest = Message<"yeying.api.mail.VerifyMailRequest"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.mail.VerifyMailRequestBody body = 2;
   */
  body?: VerifyMailRequestBody;
};

/**
 * Describes the message yeying.api.mail.VerifyMailRequest.
 * Use `create(VerifyMailRequestSchema)` to create a new message.
 */
export const VerifyMailRequestSchema: GenMessage<VerifyMailRequest> = /*@__PURE__*/
  messageDesc(file_yeying_api_mail_mail, 4);

/**
 * @generated from message yeying.api.mail.VerifyMailRequestBody
 */
export type VerifyMailRequestBody = Message<"yeying.api.mail.VerifyMailRequestBody"> & {
  /**
   * 收件箱
   *
   * @generated from field: string toMail = 1;
   */
  toMail: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message yeying.api.mail.VerifyMailRequestBody.
 * Use `create(VerifyMailRequestBodySchema)` to create a new message.
 */
export const VerifyMailRequestBodySchema: GenMessage<VerifyMailRequestBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_mail_mail, 5);

/**
 * *
 * 验证码验证响应体
 *
 * @generated from message yeying.api.mail.VerifyMailResponse
 */
export type VerifyMailResponse = Message<"yeying.api.mail.VerifyMailResponse"> & {
  /**
   * @generated from field: yeying.api.common.MessageHeader header = 1;
   */
  header?: MessageHeader;

  /**
   * @generated from field: yeying.api.mail.VerifyMailResponseBody body = 2;
   */
  body?: VerifyMailResponseBody;
};

/**
 * Describes the message yeying.api.mail.VerifyMailResponse.
 * Use `create(VerifyMailResponseSchema)` to create a new message.
 */
export const VerifyMailResponseSchema: GenMessage<VerifyMailResponse> = /*@__PURE__*/
  messageDesc(file_yeying_api_mail_mail, 6);

/**
 * @generated from message yeying.api.mail.VerifyMailResponseBody
 */
export type VerifyMailResponseBody = Message<"yeying.api.mail.VerifyMailResponseBody"> & {
  /**
   * @generated from field: yeying.api.common.ResponseStatus status = 1;
   */
  status?: ResponseStatus;
};

/**
 * Describes the message yeying.api.mail.VerifyMailResponseBody.
 * Use `create(VerifyMailResponseBodySchema)` to create a new message.
 */
export const VerifyMailResponseBodySchema: GenMessage<VerifyMailResponseBody> = /*@__PURE__*/
  messageDesc(file_yeying_api_mail_mail, 7);

/**
 * *
 * 定义一个邮件服务
 *
 * @generated from service yeying.api.mail.Mail
 */
export const Mail: GenService<{
  /**
   * @generated from rpc yeying.api.mail.Mail.Send
   */
  send: {
    methodKind: "unary";
    input: typeof SendMailRequestSchema;
    output: typeof SendMailResponseSchema;
  },
  /**
   * @generated from rpc yeying.api.mail.Mail.Verify
   */
  verify: {
    methodKind: "unary";
    input: typeof VerifyMailRequestSchema;
    output: typeof VerifyMailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yeying_api_mail_mail, 0);

