// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yeying/api/common/code.proto
// Protobuf Java Version: 4.29.3

package yeying.api.common;

public final class Code {
  private Code() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Code.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * *
   * 接口的响应状态码定义遵循的规则，必须包含以下4个说明：
   * 1、编码
   * 2、编号
   * 3、含义
   * 4、使用场景
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ResponseCodeEnum}
   */
  public enum ResponseCodeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>RESPONSE_CODE_UNKNOWN = 0;</code>
     */
    RESPONSE_CODE_UNKNOWN(0),
    /**
     * <pre>
     * *
     * 含义：操作完成
     * 使用场景：成功创建、成功提交
     * </pre>
     *
     * <code>OK = 1;</code>
     */
    OK(1),
    /**
     * <pre>
     * *
     * 含义：提供的参数无效或不符合预期
     * 使用场景：当接收到客户端请求参数不正确时返回
     * </pre>
     *
     * <code>INVALID_ARGUMENT = 2;</code>
     */
    INVALID_ARGUMENT(2),
    /**
     * <pre>
     * *
     * 含义：请求未通过身份验证
     * 使用场景：当请求需要身份验证但未提供有效凭据时返回
     * </pre>
     *
     * <code>UNAUTHENTICATED = 3;</code>
     */
    UNAUTHENTICATED(3),
    /**
     * <pre>
     * *
     * 含义：请求无法被执行，因为没有足够的权限
     * 使用场景：当客户端没有执行请求所需操作的权限时返回
     * </pre>
     *
     * <code>PERMISSION_DENIED = 4;</code>
     */
    PERMISSION_DENIED(4),
    /**
     * <pre>
     * *
     * 含义：请求对象或资源未找到
     * 使用场景：当请求的对象或资源不存在时返回
     * </pre>
     *
     * <code>NOT_FOUND = 5;</code>
     */
    NOT_FOUND(5),
    /**
     * <pre>
     * *
     * 含义：请求创建的对象已经存在
     * 使用场景：当请求创建的对象（如用户、资源等）已经存在时返回
     * </pre>
     *
     * <code>ALREADY_EXISTS = 6;</code>
     */
    ALREADY_EXISTS(6),
    /**
     * <pre>
     * *
     * 含义：超过了资源使用限制
     * 使用场景：当请求操作超过了预先设定的限制时返回
     * </pre>
     *
     * <code>LIMIT_EXCEEDED = 7;</code>
     */
    LIMIT_EXCEEDED(7),
    /**
     * <pre>
     * *
     * 含义：请求的服务当前不可用
     * 使用场景：当请求的服务不可用（例如服务器维护、过载等）时返回
     * </pre>
     *
     * <code>UNAVAILABLE = 8;</code>
     */
    UNAVAILABLE(8),
    /**
     * <pre>
     * *
     * 含义：未知错误
     * 使用场景：当出现未知错误时返回或无法精确匹配到其他错误码时使用
     * </pre>
     *
     * <code>UNKNOWN_ERROR = 9;</code>
     */
    UNKNOWN_ERROR(9),
    /**
     * <pre>
     * *
     * 含义：网络错误
     * 使用场景：应为网络错误，无法发送到服务器
     * </pre>
     *
     * <code>NETWORK_ERROR = 10;</code>
     */
    NETWORK_ERROR(10),
    /**
     * <pre>
     * *
     * 含义：无效证书
     * 使用场景：浏览器无法识别证书，在浏览器中添加为受信任证书
     * </pre>
     *
     * <code>INVALID_CERT = 11;</code>
     */
    INVALID_CERT(11),
    /**
     * <pre>
     * *
     * 含义：不支持
     * 使用场景：接口、服务不支持
     * </pre>
     *
     * <code>NOT_SUPPORTED = 12;</code>
     */
    NOT_SUPPORTED(12),
    /**
     * <pre>
     * *
     * 含义：数据损坏
     * 使用场景：验证数据的签名不通过，当和存储供应商签约资产时，用户发送到供应商的数据验证签名不通过
     * </pre>
     *
     * <code>DATA_CORRUPTED = 13;</code>
     */
    DATA_CORRUPTED(13),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ResponseCodeEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>RESPONSE_CODE_UNKNOWN = 0;</code>
     */
    public static final int RESPONSE_CODE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * *
     * 含义：操作完成
     * 使用场景：成功创建、成功提交
     * </pre>
     *
     * <code>OK = 1;</code>
     */
    public static final int OK_VALUE = 1;
    /**
     * <pre>
     * *
     * 含义：提供的参数无效或不符合预期
     * 使用场景：当接收到客户端请求参数不正确时返回
     * </pre>
     *
     * <code>INVALID_ARGUMENT = 2;</code>
     */
    public static final int INVALID_ARGUMENT_VALUE = 2;
    /**
     * <pre>
     * *
     * 含义：请求未通过身份验证
     * 使用场景：当请求需要身份验证但未提供有效凭据时返回
     * </pre>
     *
     * <code>UNAUTHENTICATED = 3;</code>
     */
    public static final int UNAUTHENTICATED_VALUE = 3;
    /**
     * <pre>
     * *
     * 含义：请求无法被执行，因为没有足够的权限
     * 使用场景：当客户端没有执行请求所需操作的权限时返回
     * </pre>
     *
     * <code>PERMISSION_DENIED = 4;</code>
     */
    public static final int PERMISSION_DENIED_VALUE = 4;
    /**
     * <pre>
     * *
     * 含义：请求对象或资源未找到
     * 使用场景：当请求的对象或资源不存在时返回
     * </pre>
     *
     * <code>NOT_FOUND = 5;</code>
     */
    public static final int NOT_FOUND_VALUE = 5;
    /**
     * <pre>
     * *
     * 含义：请求创建的对象已经存在
     * 使用场景：当请求创建的对象（如用户、资源等）已经存在时返回
     * </pre>
     *
     * <code>ALREADY_EXISTS = 6;</code>
     */
    public static final int ALREADY_EXISTS_VALUE = 6;
    /**
     * <pre>
     * *
     * 含义：超过了资源使用限制
     * 使用场景：当请求操作超过了预先设定的限制时返回
     * </pre>
     *
     * <code>LIMIT_EXCEEDED = 7;</code>
     */
    public static final int LIMIT_EXCEEDED_VALUE = 7;
    /**
     * <pre>
     * *
     * 含义：请求的服务当前不可用
     * 使用场景：当请求的服务不可用（例如服务器维护、过载等）时返回
     * </pre>
     *
     * <code>UNAVAILABLE = 8;</code>
     */
    public static final int UNAVAILABLE_VALUE = 8;
    /**
     * <pre>
     * *
     * 含义：未知错误
     * 使用场景：当出现未知错误时返回或无法精确匹配到其他错误码时使用
     * </pre>
     *
     * <code>UNKNOWN_ERROR = 9;</code>
     */
    public static final int UNKNOWN_ERROR_VALUE = 9;
    /**
     * <pre>
     * *
     * 含义：网络错误
     * 使用场景：应为网络错误，无法发送到服务器
     * </pre>
     *
     * <code>NETWORK_ERROR = 10;</code>
     */
    public static final int NETWORK_ERROR_VALUE = 10;
    /**
     * <pre>
     * *
     * 含义：无效证书
     * 使用场景：浏览器无法识别证书，在浏览器中添加为受信任证书
     * </pre>
     *
     * <code>INVALID_CERT = 11;</code>
     */
    public static final int INVALID_CERT_VALUE = 11;
    /**
     * <pre>
     * *
     * 含义：不支持
     * 使用场景：接口、服务不支持
     * </pre>
     *
     * <code>NOT_SUPPORTED = 12;</code>
     */
    public static final int NOT_SUPPORTED_VALUE = 12;
    /**
     * <pre>
     * *
     * 含义：数据损坏
     * 使用场景：验证数据的签名不通过，当和存储供应商签约资产时，用户发送到供应商的数据验证签名不通过
     * </pre>
     *
     * <code>DATA_CORRUPTED = 13;</code>
     */
    public static final int DATA_CORRUPTED_VALUE = 13;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCodeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResponseCodeEnum forNumber(int value) {
      switch (value) {
        case 0: return RESPONSE_CODE_UNKNOWN;
        case 1: return OK;
        case 2: return INVALID_ARGUMENT;
        case 3: return UNAUTHENTICATED;
        case 4: return PERMISSION_DENIED;
        case 5: return NOT_FOUND;
        case 6: return ALREADY_EXISTS;
        case 7: return LIMIT_EXCEEDED;
        case 8: return UNAVAILABLE;
        case 9: return UNKNOWN_ERROR;
        case 10: return NETWORK_ERROR;
        case 11: return INVALID_CERT;
        case 12: return NOT_SUPPORTED;
        case 13: return DATA_CORRUPTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseCodeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseCodeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseCodeEnum>() {
            public ResponseCodeEnum findValueByNumber(int number) {
              return ResponseCodeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponseCodeEnum[] VALUES = values();

    public static ResponseCodeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseCodeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ResponseCodeEnum)
  }

  /**
   * <pre>
   * *
   * 合约的状态码需要遵守的规则：
   * 1、编码
   * 2、编号
   * 3、含义
   * 4、使用场景
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ContractStatusEnum}
   */
  public enum ContractStatusEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>CONTRACT_STATUS_UNKNOWN = 0;</code>
     */
    CONTRACT_STATUS_UNKNOWN(0),
    /**
     * <pre>
     * 未生效，拟定了一份合同，参与方没有完全签字
     * </pre>
     *
     * <code>CONTRACT_STATUS_INACTIVATED = 1;</code>
     */
    CONTRACT_STATUS_INACTIVATED(1),
    /**
     * <pre>
     * 生效中，合同的参与方都已签字认可，合同已经开始工作
     * </pre>
     *
     * <code>CONTRACT_STATUS_ACTIVATED = 2;</code>
     */
    CONTRACT_STATUS_ACTIVATED(2),
    /**
     * <pre>
     * 过期了，合同已经过期了，合同已停止工作
     * </pre>
     *
     * <code>CONTRACT_STATUS_EXPIRED = 3;</code>
     */
    CONTRACT_STATUS_EXPIRED(3),
    /**
     * <pre>
     * 终止了，合同的参与方中有人主动退出了合同
     * </pre>
     *
     * <code>CONTRACT_STATUS_CANCELED = 4;</code>
     */
    CONTRACT_STATUS_CANCELED(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ContractStatusEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>CONTRACT_STATUS_UNKNOWN = 0;</code>
     */
    public static final int CONTRACT_STATUS_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 未生效，拟定了一份合同，参与方没有完全签字
     * </pre>
     *
     * <code>CONTRACT_STATUS_INACTIVATED = 1;</code>
     */
    public static final int CONTRACT_STATUS_INACTIVATED_VALUE = 1;
    /**
     * <pre>
     * 生效中，合同的参与方都已签字认可，合同已经开始工作
     * </pre>
     *
     * <code>CONTRACT_STATUS_ACTIVATED = 2;</code>
     */
    public static final int CONTRACT_STATUS_ACTIVATED_VALUE = 2;
    /**
     * <pre>
     * 过期了，合同已经过期了，合同已停止工作
     * </pre>
     *
     * <code>CONTRACT_STATUS_EXPIRED = 3;</code>
     */
    public static final int CONTRACT_STATUS_EXPIRED_VALUE = 3;
    /**
     * <pre>
     * 终止了，合同的参与方中有人主动退出了合同
     * </pre>
     *
     * <code>CONTRACT_STATUS_CANCELED = 4;</code>
     */
    public static final int CONTRACT_STATUS_CANCELED_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContractStatusEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ContractStatusEnum forNumber(int value) {
      switch (value) {
        case 0: return CONTRACT_STATUS_UNKNOWN;
        case 1: return CONTRACT_STATUS_INACTIVATED;
        case 2: return CONTRACT_STATUS_ACTIVATED;
        case 3: return CONTRACT_STATUS_EXPIRED;
        case 4: return CONTRACT_STATUS_CANCELED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ContractStatusEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ContractStatusEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ContractStatusEnum>() {
            public ContractStatusEnum findValueByNumber(int number) {
              return ContractStatusEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(1);
    }

    private static final ContractStatusEnum[] VALUES = values();

    public static ContractStatusEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ContractStatusEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ContractStatusEnum)
  }

  /**
   * <pre>
   * 语言类型
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.LanguageCodeEnum}
   */
  public enum LanguageCodeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>LANGUAGE_CODE_UNKNOWN = 0;</code>
     */
    LANGUAGE_CODE_UNKNOWN(0),
    /**
     * <pre>
     * 简体中文
     * </pre>
     *
     * <code>LANGUAGE_CODE_ZH_CH = 1;</code>
     */
    LANGUAGE_CODE_ZH_CH(1),
    /**
     * <pre>
     * 美国英语
     * </pre>
     *
     * <code>LANGUAGE_CODE_EN_US = 2;</code>
     */
    LANGUAGE_CODE_EN_US(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        LanguageCodeEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>LANGUAGE_CODE_UNKNOWN = 0;</code>
     */
    public static final int LANGUAGE_CODE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 简体中文
     * </pre>
     *
     * <code>LANGUAGE_CODE_ZH_CH = 1;</code>
     */
    public static final int LANGUAGE_CODE_ZH_CH_VALUE = 1;
    /**
     * <pre>
     * 美国英语
     * </pre>
     *
     * <code>LANGUAGE_CODE_EN_US = 2;</code>
     */
    public static final int LANGUAGE_CODE_EN_US_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LanguageCodeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LanguageCodeEnum forNumber(int value) {
      switch (value) {
        case 0: return LANGUAGE_CODE_UNKNOWN;
        case 1: return LANGUAGE_CODE_ZH_CH;
        case 2: return LANGUAGE_CODE_EN_US;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LanguageCodeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LanguageCodeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LanguageCodeEnum>() {
            public LanguageCodeEnum findValueByNumber(int number) {
              return LanguageCodeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(2);
    }

    private static final LanguageCodeEnum[] VALUES = values();

    public static LanguageCodeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LanguageCodeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.LanguageCodeEnum)
  }

  /**
   * <pre>
   * 应用编码，每个应用都有一个类别，每个应用都可以绑定都个服务编码。
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ApplicationCodeEnum}
   */
  public enum ApplicationCodeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>APPLICATION_CODE_UNKNOWN = 0;</code>
     */
    APPLICATION_CODE_UNKNOWN(0),
    /**
     * <pre>
     * 社区集市，提供应用、服务以及智能合约的发布、上线、下线等服务，用户可以在应用集市组装自己的应用；
     * </pre>
     *
     * <code>APPLICATION_CODE_MARKET = 1;</code>
     */
    APPLICATION_CODE_MARKET(1),
    /**
     * <pre>
     * 资产应用
     * </pre>
     *
     * <code>APPLICATION_CODE_ASSET = 2;</code>
     */
    APPLICATION_CODE_ASSET(2),
    /**
     * <pre>
     * 知识库应用
     * </pre>
     *
     * <code>APPLICATION_CODE_KNOWLEDGE = 3;</code>
     */
    APPLICATION_CODE_KNOWLEDGE(3),
    /**
     * <pre>
     * 智能管家应用，包括钱包
     * </pre>
     *
     * <code>APPLICATION_CODE_KEEPER = 4;</code>
     */
    APPLICATION_CODE_KEEPER(4),
    /**
     * <pre>
     * 社交应用
     * </pre>
     *
     * <code>APPLICATION_CODE_SOCIAL = 5;</code>
     */
    APPLICATION_CODE_SOCIAL(5),
    /**
     * <pre>
     * 工作台应用
     * </pre>
     *
     * <code>APPLICATION_CODE_WORKBENCH = 6;</code>
     */
    APPLICATION_CODE_WORKBENCH(6),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ApplicationCodeEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>APPLICATION_CODE_UNKNOWN = 0;</code>
     */
    public static final int APPLICATION_CODE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 社区集市，提供应用、服务以及智能合约的发布、上线、下线等服务，用户可以在应用集市组装自己的应用；
     * </pre>
     *
     * <code>APPLICATION_CODE_MARKET = 1;</code>
     */
    public static final int APPLICATION_CODE_MARKET_VALUE = 1;
    /**
     * <pre>
     * 资产应用
     * </pre>
     *
     * <code>APPLICATION_CODE_ASSET = 2;</code>
     */
    public static final int APPLICATION_CODE_ASSET_VALUE = 2;
    /**
     * <pre>
     * 知识库应用
     * </pre>
     *
     * <code>APPLICATION_CODE_KNOWLEDGE = 3;</code>
     */
    public static final int APPLICATION_CODE_KNOWLEDGE_VALUE = 3;
    /**
     * <pre>
     * 智能管家应用，包括钱包
     * </pre>
     *
     * <code>APPLICATION_CODE_KEEPER = 4;</code>
     */
    public static final int APPLICATION_CODE_KEEPER_VALUE = 4;
    /**
     * <pre>
     * 社交应用
     * </pre>
     *
     * <code>APPLICATION_CODE_SOCIAL = 5;</code>
     */
    public static final int APPLICATION_CODE_SOCIAL_VALUE = 5;
    /**
     * <pre>
     * 工作台应用
     * </pre>
     *
     * <code>APPLICATION_CODE_WORKBENCH = 6;</code>
     */
    public static final int APPLICATION_CODE_WORKBENCH_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ApplicationCodeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ApplicationCodeEnum forNumber(int value) {
      switch (value) {
        case 0: return APPLICATION_CODE_UNKNOWN;
        case 1: return APPLICATION_CODE_MARKET;
        case 2: return APPLICATION_CODE_ASSET;
        case 3: return APPLICATION_CODE_KNOWLEDGE;
        case 4: return APPLICATION_CODE_KEEPER;
        case 5: return APPLICATION_CODE_SOCIAL;
        case 6: return APPLICATION_CODE_WORKBENCH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApplicationCodeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ApplicationCodeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApplicationCodeEnum>() {
            public ApplicationCodeEnum findValueByNumber(int number) {
              return ApplicationCodeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(3);
    }

    private static final ApplicationCodeEnum[] VALUES = values();

    public static ApplicationCodeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ApplicationCodeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ApplicationCodeEnum)
  }

  /**
   * <pre>
   * 服务编码，每个服务都可以绑定多个API编码，对外提供多套服务接口
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ServiceCodeEnum}
   */
  public enum ServiceCodeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>SERVICE_CODE_UNKNOWN = 0;</code>
     */
    SERVICE_CODE_UNKNOWN(0),
    /**
     * <pre>
     * 网络节点供应商
     * </pre>
     *
     * <code>SERVICE_CODE_NODE = 1;</code>
     */
    SERVICE_CODE_NODE(1),
    /**
     * <pre>
     * 仓储服务供应商
     * </pre>
     *
     * <code>SERVICE_CODE_WAREHOUSE = 2;</code>
     */
    SERVICE_CODE_WAREHOUSE(2),
    /**
     * <pre>
     * 智能体供应商
     * </pre>
     *
     * <code>SERVICE_CODE_AGENT = 3;</code>
     */
    SERVICE_CODE_AGENT(3),
    /**
     * <pre>
     * 模型上下文供应商
     * </pre>
     *
     * <code>SERVICE_CODE_MCP = 4;</code>
     */
    SERVICE_CODE_MCP(4),
    /**
     * <pre>
     * 机器人服务供应商，提供各种模型和算法服务
     * </pre>
     *
     * <code>SERVICE_CODE_AI = 5;</code>
     */
    SERVICE_CODE_AI(5),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ServiceCodeEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>SERVICE_CODE_UNKNOWN = 0;</code>
     */
    public static final int SERVICE_CODE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 网络节点供应商
     * </pre>
     *
     * <code>SERVICE_CODE_NODE = 1;</code>
     */
    public static final int SERVICE_CODE_NODE_VALUE = 1;
    /**
     * <pre>
     * 仓储服务供应商
     * </pre>
     *
     * <code>SERVICE_CODE_WAREHOUSE = 2;</code>
     */
    public static final int SERVICE_CODE_WAREHOUSE_VALUE = 2;
    /**
     * <pre>
     * 智能体供应商
     * </pre>
     *
     * <code>SERVICE_CODE_AGENT = 3;</code>
     */
    public static final int SERVICE_CODE_AGENT_VALUE = 3;
    /**
     * <pre>
     * 模型上下文供应商
     * </pre>
     *
     * <code>SERVICE_CODE_MCP = 4;</code>
     */
    public static final int SERVICE_CODE_MCP_VALUE = 4;
    /**
     * <pre>
     * 机器人服务供应商，提供各种模型和算法服务
     * </pre>
     *
     * <code>SERVICE_CODE_AI = 5;</code>
     */
    public static final int SERVICE_CODE_AI_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServiceCodeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ServiceCodeEnum forNumber(int value) {
      switch (value) {
        case 0: return SERVICE_CODE_UNKNOWN;
        case 1: return SERVICE_CODE_NODE;
        case 2: return SERVICE_CODE_WAREHOUSE;
        case 3: return SERVICE_CODE_AGENT;
        case 4: return SERVICE_CODE_MCP;
        case 5: return SERVICE_CODE_AI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServiceCodeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServiceCodeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceCodeEnum>() {
            public ServiceCodeEnum findValueByNumber(int number) {
              return ServiceCodeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(4);
    }

    private static final ServiceCodeEnum[] VALUES = values();

    public static ServiceCodeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServiceCodeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ServiceCodeEnum)
  }

  /**
   * <pre>
   * API编码，针对服务做一些原子的、标准化的工作，方便第三方接入区块链网络，也方便服务使用者集成使用
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ApiCodeEnum}
   */
  public enum ApiCodeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>API_CODE_UNKNOWN = 0;</code>
     */
    API_CODE_UNKNOWN(0),
    /**
     * <pre>
     * 用户服务
     * </pre>
     *
     * <code>API_CODE_USER = 1;</code>
     */
    API_CODE_USER(1),
    /**
     * <pre>
     * 身份服务
     * </pre>
     *
     * <code>API_CODE_IDENTITY = 2;</code>
     */
    API_CODE_IDENTITY(2),
    /**
     * <pre>
     * 大模型服务API
     * </pre>
     *
     * <code>API_CODE_LLM_SERVICE = 3;</code>
     */
    API_CODE_LLM_SERVICE(3),
    /**
     * <pre>
     * 大模型供应商API
     * </pre>
     *
     * <code>API_CODE_LLM_PROVIDER = 4;</code>
     */
    API_CODE_LLM_PROVIDER(4),
    /**
     * <pre>
     * 资产服务API
     * </pre>
     *
     * <code>API_CODE_ASSET_SERVICE = 5;</code>
     */
    API_CODE_ASSET_SERVICE(5),
    /**
     * <pre>
     * 资产块API
     * </pre>
     *
     * <code>API_CODE_ASSET_BLOCK = 6;</code>
     */
    API_CODE_ASSET_BLOCK(6),
    /**
     * <pre>
     * 资产链接API
     * </pre>
     *
     * <code>API_CODE_ASSET_LINK = 7;</code>
     */
    API_CODE_ASSET_LINK(7),
    /**
     * <pre>
     * 资产命名空间API
     * </pre>
     *
     * <code>API_CODE_ASSET_NAMESPACE = 8;</code>
     */
    API_CODE_ASSET_NAMESPACE(8),
    /**
     * <pre>
     * 资产回收站API
     * </pre>
     *
     * <code>API_CODE_ASSET_RECYCLE = 9;</code>
     */
    API_CODE_ASSET_RECYCLE(9),
    /**
     * <pre>
     * 证书服务
     * </pre>
     *
     * <code>API_CODE_CERTIFICATE = 10;</code>
     */
    API_CODE_CERTIFICATE(10),
    /**
     * <pre>
     * 存储服务
     * </pre>
     *
     * <code>API_CODE_STORAGE = 11;</code>
     */
    API_CODE_STORAGE(11),
    /**
     * <pre>
     * 应用仓库
     * </pre>
     *
     * <code>API_CODE_APPLICATION = 12;</code>
     */
    API_CODE_APPLICATION(12),
    /**
     * <pre>
     * 事件服务
     * </pre>
     *
     * <code>API_CODE_EVENT = 13;</code>
     */
    API_CODE_EVENT(13),
    /**
     * <pre>
     * 邀请码服务
     * </pre>
     *
     * <code>API_CODE_INVITATION = 14;</code>
     */
    API_CODE_INVITATION(14),
    /**
     * <pre>
     * 服务接口
     * </pre>
     *
     * <code>API_CODE_SERVICE = 15;</code>
     */
    API_CODE_SERVICE(15),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ApiCodeEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>API_CODE_UNKNOWN = 0;</code>
     */
    public static final int API_CODE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 用户服务
     * </pre>
     *
     * <code>API_CODE_USER = 1;</code>
     */
    public static final int API_CODE_USER_VALUE = 1;
    /**
     * <pre>
     * 身份服务
     * </pre>
     *
     * <code>API_CODE_IDENTITY = 2;</code>
     */
    public static final int API_CODE_IDENTITY_VALUE = 2;
    /**
     * <pre>
     * 大模型服务API
     * </pre>
     *
     * <code>API_CODE_LLM_SERVICE = 3;</code>
     */
    public static final int API_CODE_LLM_SERVICE_VALUE = 3;
    /**
     * <pre>
     * 大模型供应商API
     * </pre>
     *
     * <code>API_CODE_LLM_PROVIDER = 4;</code>
     */
    public static final int API_CODE_LLM_PROVIDER_VALUE = 4;
    /**
     * <pre>
     * 资产服务API
     * </pre>
     *
     * <code>API_CODE_ASSET_SERVICE = 5;</code>
     */
    public static final int API_CODE_ASSET_SERVICE_VALUE = 5;
    /**
     * <pre>
     * 资产块API
     * </pre>
     *
     * <code>API_CODE_ASSET_BLOCK = 6;</code>
     */
    public static final int API_CODE_ASSET_BLOCK_VALUE = 6;
    /**
     * <pre>
     * 资产链接API
     * </pre>
     *
     * <code>API_CODE_ASSET_LINK = 7;</code>
     */
    public static final int API_CODE_ASSET_LINK_VALUE = 7;
    /**
     * <pre>
     * 资产命名空间API
     * </pre>
     *
     * <code>API_CODE_ASSET_NAMESPACE = 8;</code>
     */
    public static final int API_CODE_ASSET_NAMESPACE_VALUE = 8;
    /**
     * <pre>
     * 资产回收站API
     * </pre>
     *
     * <code>API_CODE_ASSET_RECYCLE = 9;</code>
     */
    public static final int API_CODE_ASSET_RECYCLE_VALUE = 9;
    /**
     * <pre>
     * 证书服务
     * </pre>
     *
     * <code>API_CODE_CERTIFICATE = 10;</code>
     */
    public static final int API_CODE_CERTIFICATE_VALUE = 10;
    /**
     * <pre>
     * 存储服务
     * </pre>
     *
     * <code>API_CODE_STORAGE = 11;</code>
     */
    public static final int API_CODE_STORAGE_VALUE = 11;
    /**
     * <pre>
     * 应用仓库
     * </pre>
     *
     * <code>API_CODE_APPLICATION = 12;</code>
     */
    public static final int API_CODE_APPLICATION_VALUE = 12;
    /**
     * <pre>
     * 事件服务
     * </pre>
     *
     * <code>API_CODE_EVENT = 13;</code>
     */
    public static final int API_CODE_EVENT_VALUE = 13;
    /**
     * <pre>
     * 邀请码服务
     * </pre>
     *
     * <code>API_CODE_INVITATION = 14;</code>
     */
    public static final int API_CODE_INVITATION_VALUE = 14;
    /**
     * <pre>
     * 服务接口
     * </pre>
     *
     * <code>API_CODE_SERVICE = 15;</code>
     */
    public static final int API_CODE_SERVICE_VALUE = 15;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ApiCodeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ApiCodeEnum forNumber(int value) {
      switch (value) {
        case 0: return API_CODE_UNKNOWN;
        case 1: return API_CODE_USER;
        case 2: return API_CODE_IDENTITY;
        case 3: return API_CODE_LLM_SERVICE;
        case 4: return API_CODE_LLM_PROVIDER;
        case 5: return API_CODE_ASSET_SERVICE;
        case 6: return API_CODE_ASSET_BLOCK;
        case 7: return API_CODE_ASSET_LINK;
        case 8: return API_CODE_ASSET_NAMESPACE;
        case 9: return API_CODE_ASSET_RECYCLE;
        case 10: return API_CODE_CERTIFICATE;
        case 11: return API_CODE_STORAGE;
        case 12: return API_CODE_APPLICATION;
        case 13: return API_CODE_EVENT;
        case 14: return API_CODE_INVITATION;
        case 15: return API_CODE_SERVICE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApiCodeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ApiCodeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApiCodeEnum>() {
            public ApiCodeEnum findValueByNumber(int number) {
              return ApiCodeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(5);
    }

    private static final ApiCodeEnum[] VALUES = values();

    public static ApiCodeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ApiCodeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ApiCodeEnum)
  }

  /**
   * <pre>
   * 图片格式
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ImageFormatEnum}
   */
  public enum ImageFormatEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知图片格式，是一种占位符
     * </pre>
     *
     * <code>IMAGE_FORMAT_UNKNOWN = 0;</code>
     */
    IMAGE_FORMAT_UNKNOWN(0),
    /**
     * <pre>
     * PNG格式
     * </pre>
     *
     * <code>IMAGE_FORMAT_PNG = 1;</code>
     */
    IMAGE_FORMAT_PNG(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ImageFormatEnum.class.getName());
    }
    /**
     * <pre>
     * 未知图片格式，是一种占位符
     * </pre>
     *
     * <code>IMAGE_FORMAT_UNKNOWN = 0;</code>
     */
    public static final int IMAGE_FORMAT_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * PNG格式
     * </pre>
     *
     * <code>IMAGE_FORMAT_PNG = 1;</code>
     */
    public static final int IMAGE_FORMAT_PNG_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ImageFormatEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ImageFormatEnum forNumber(int value) {
      switch (value) {
        case 0: return IMAGE_FORMAT_UNKNOWN;
        case 1: return IMAGE_FORMAT_PNG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ImageFormatEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ImageFormatEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ImageFormatEnum>() {
            public ImageFormatEnum findValueByNumber(int number) {
              return ImageFormatEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(6);
    }

    private static final ImageFormatEnum[] VALUES = values();

    public static ImageFormatEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ImageFormatEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ImageFormatEnum)
  }

  /**
   * <pre>
   * 数字格式
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.DigitalFormatEnum}
   */
  public enum DigitalFormatEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知数字格式，是一种占位符
     * </pre>
     *
     * <code>DIGITAL_FORMAT_UNKNOWN = 0;</code>
     */
    DIGITAL_FORMAT_UNKNOWN(0),
    /**
     * <pre>
     * 文本
     * </pre>
     *
     * <code>DIGITAL_FORMAT_TEXT = 1;</code>
     */
    DIGITAL_FORMAT_TEXT(1),
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>DIGITAL_FORMAT_IMAGE = 2;</code>
     */
    DIGITAL_FORMAT_IMAGE(2),
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>DIGITAL_FORMAT_VIDEO = 3;</code>
     */
    DIGITAL_FORMAT_VIDEO(3),
    /**
     * <pre>
     * 音频
     * </pre>
     *
     * <code>DIGITAL_FORMAT_AUDIO = 4;</code>
     */
    DIGITAL_FORMAT_AUDIO(4),
    /**
     * <pre>
     * 应用
     * </pre>
     *
     * <code>DIGITAL_FORMAT_APP = 5;</code>
     */
    DIGITAL_FORMAT_APP(5),
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>DIGITAL_FORMAT_OTHER = 10000;</code>
     */
    DIGITAL_FORMAT_OTHER(10000),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        DigitalFormatEnum.class.getName());
    }
    /**
     * <pre>
     * 未知数字格式，是一种占位符
     * </pre>
     *
     * <code>DIGITAL_FORMAT_UNKNOWN = 0;</code>
     */
    public static final int DIGITAL_FORMAT_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 文本
     * </pre>
     *
     * <code>DIGITAL_FORMAT_TEXT = 1;</code>
     */
    public static final int DIGITAL_FORMAT_TEXT_VALUE = 1;
    /**
     * <pre>
     * 图片
     * </pre>
     *
     * <code>DIGITAL_FORMAT_IMAGE = 2;</code>
     */
    public static final int DIGITAL_FORMAT_IMAGE_VALUE = 2;
    /**
     * <pre>
     * 视频
     * </pre>
     *
     * <code>DIGITAL_FORMAT_VIDEO = 3;</code>
     */
    public static final int DIGITAL_FORMAT_VIDEO_VALUE = 3;
    /**
     * <pre>
     * 音频
     * </pre>
     *
     * <code>DIGITAL_FORMAT_AUDIO = 4;</code>
     */
    public static final int DIGITAL_FORMAT_AUDIO_VALUE = 4;
    /**
     * <pre>
     * 应用
     * </pre>
     *
     * <code>DIGITAL_FORMAT_APP = 5;</code>
     */
    public static final int DIGITAL_FORMAT_APP_VALUE = 5;
    /**
     * <pre>
     * 未知
     * </pre>
     *
     * <code>DIGITAL_FORMAT_OTHER = 10000;</code>
     */
    public static final int DIGITAL_FORMAT_OTHER_VALUE = 10000;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DigitalFormatEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DigitalFormatEnum forNumber(int value) {
      switch (value) {
        case 0: return DIGITAL_FORMAT_UNKNOWN;
        case 1: return DIGITAL_FORMAT_TEXT;
        case 2: return DIGITAL_FORMAT_IMAGE;
        case 3: return DIGITAL_FORMAT_VIDEO;
        case 4: return DIGITAL_FORMAT_AUDIO;
        case 5: return DIGITAL_FORMAT_APP;
        case 10000: return DIGITAL_FORMAT_OTHER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DigitalFormatEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DigitalFormatEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DigitalFormatEnum>() {
            public DigitalFormatEnum findValueByNumber(int number) {
              return DigitalFormatEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(7);
    }

    private static final DigitalFormatEnum[] VALUES = values();

    public static DigitalFormatEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DigitalFormatEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.DigitalFormatEnum)
  }

  /**
   * <pre>
   * 内容格式
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ContentFormatEnum}
   */
  public enum ContentFormatEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONTENT_FORMAT_UNKNOWN = 0;</code>
     */
    CONTENT_FORMAT_UNKNOWN(0),
    /**
     * <code>CONTENT_FORMAT_URL = 1;</code>
     */
    CONTENT_FORMAT_URL(1),
    /**
     * <code>CONTENT_FORMAT_BASE64 = 2;</code>
     */
    CONTENT_FORMAT_BASE64(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ContentFormatEnum.class.getName());
    }
    /**
     * <code>CONTENT_FORMAT_UNKNOWN = 0;</code>
     */
    public static final int CONTENT_FORMAT_UNKNOWN_VALUE = 0;
    /**
     * <code>CONTENT_FORMAT_URL = 1;</code>
     */
    public static final int CONTENT_FORMAT_URL_VALUE = 1;
    /**
     * <code>CONTENT_FORMAT_BASE64 = 2;</code>
     */
    public static final int CONTENT_FORMAT_BASE64_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ContentFormatEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ContentFormatEnum forNumber(int value) {
      switch (value) {
        case 0: return CONTENT_FORMAT_UNKNOWN;
        case 1: return CONTENT_FORMAT_URL;
        case 2: return CONTENT_FORMAT_BASE64;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ContentFormatEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ContentFormatEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ContentFormatEnum>() {
            public ContentFormatEnum findValueByNumber(int number) {
              return ContentFormatEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(8);
    }

    private static final ContentFormatEnum[] VALUES = values();

    public static ContentFormatEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ContentFormatEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ContentFormatEnum)
  }

  /**
   * <pre>
   * 会话场景
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.SessionSceneEnum}
   */
  public enum SessionSceneEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>SESSION_SCENE_UNKNOWN = 0;</code>
     */
    SESSION_SCENE_UNKNOWN(0),
    /**
     * <pre>
     * 对话
     * </pre>
     *
     * <code>SESSION_SCENE_DIALOGUE = 1;</code>
     */
    SESSION_SCENE_DIALOGUE(1),
    /**
     * <pre>
     * 作图
     * </pre>
     *
     * <code>SESSION_SCENE_DRAWING = 2;</code>
     */
    SESSION_SCENE_DRAWING(2),
    /**
     * <pre>
     * 翻译
     * </pre>
     *
     * <code>SESSION_SCENE_TRANSLATION = 3;</code>
     */
    SESSION_SCENE_TRANSLATION(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SessionSceneEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>SESSION_SCENE_UNKNOWN = 0;</code>
     */
    public static final int SESSION_SCENE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 对话
     * </pre>
     *
     * <code>SESSION_SCENE_DIALOGUE = 1;</code>
     */
    public static final int SESSION_SCENE_DIALOGUE_VALUE = 1;
    /**
     * <pre>
     * 作图
     * </pre>
     *
     * <code>SESSION_SCENE_DRAWING = 2;</code>
     */
    public static final int SESSION_SCENE_DRAWING_VALUE = 2;
    /**
     * <pre>
     * 翻译
     * </pre>
     *
     * <code>SESSION_SCENE_TRANSLATION = 3;</code>
     */
    public static final int SESSION_SCENE_TRANSLATION_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SessionSceneEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SessionSceneEnum forNumber(int value) {
      switch (value) {
        case 0: return SESSION_SCENE_UNKNOWN;
        case 1: return SESSION_SCENE_DIALOGUE;
        case 2: return SESSION_SCENE_DRAWING;
        case 3: return SESSION_SCENE_TRANSLATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SessionSceneEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SessionSceneEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SessionSceneEnum>() {
            public SessionSceneEnum findValueByNumber(int number) {
              return SessionSceneEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(9);
    }

    private static final SessionSceneEnum[] VALUES = values();

    public static SessionSceneEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SessionSceneEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.SessionSceneEnum)
  }

  /**
   * <pre>
   * 会话角色
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.SessionRoleEnum}
   */
  public enum SessionRoleEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>SESSION_ROLE_UNKNOWN = 0;</code>
     */
    SESSION_ROLE_UNKNOWN(0),
    /**
     * <pre>
     * 参与者
     * </pre>
     *
     * <code>SESSION_ROLE_PARTICIPANT = 1;</code>
     */
    SESSION_ROLE_PARTICIPANT(1),
    /**
     * <pre>
     * 管理员
     * </pre>
     *
     * <code>SESSION_ROLE_ADMIN = 2;</code>
     */
    SESSION_ROLE_ADMIN(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SessionRoleEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>SESSION_ROLE_UNKNOWN = 0;</code>
     */
    public static final int SESSION_ROLE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 参与者
     * </pre>
     *
     * <code>SESSION_ROLE_PARTICIPANT = 1;</code>
     */
    public static final int SESSION_ROLE_PARTICIPANT_VALUE = 1;
    /**
     * <pre>
     * 管理员
     * </pre>
     *
     * <code>SESSION_ROLE_ADMIN = 2;</code>
     */
    public static final int SESSION_ROLE_ADMIN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SessionRoleEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SessionRoleEnum forNumber(int value) {
      switch (value) {
        case 0: return SESSION_ROLE_UNKNOWN;
        case 1: return SESSION_ROLE_PARTICIPANT;
        case 2: return SESSION_ROLE_ADMIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SessionRoleEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SessionRoleEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SessionRoleEnum>() {
            public SessionRoleEnum findValueByNumber(int number) {
              return SessionRoleEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(10);
    }

    private static final SessionRoleEnum[] VALUES = values();

    public static SessionRoleEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SessionRoleEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.SessionRoleEnum)
  }

  /**
   * <pre>
   * 参与类型
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ParticipantTypeEnum}
   */
  public enum ParticipantTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>PARTICIPANT_TYPE_UNKNOWN = 0;</code>
     */
    PARTICIPANT_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * 服务
     * </pre>
     *
     * <code>PARTICIPANT_TYPE_SERVICE = 1;</code>
     */
    PARTICIPANT_TYPE_SERVICE(1),
    /**
     * <pre>
     * 人
     * </pre>
     *
     * <code>PARTICIPANT_TYPE_PEOPLE = 2;</code>
     */
    PARTICIPANT_TYPE_PEOPLE(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ParticipantTypeEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>PARTICIPANT_TYPE_UNKNOWN = 0;</code>
     */
    public static final int PARTICIPANT_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 服务
     * </pre>
     *
     * <code>PARTICIPANT_TYPE_SERVICE = 1;</code>
     */
    public static final int PARTICIPANT_TYPE_SERVICE_VALUE = 1;
    /**
     * <pre>
     * 人
     * </pre>
     *
     * <code>PARTICIPANT_TYPE_PEOPLE = 2;</code>
     */
    public static final int PARTICIPANT_TYPE_PEOPLE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ParticipantTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ParticipantTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return PARTICIPANT_TYPE_UNKNOWN;
        case 1: return PARTICIPANT_TYPE_SERVICE;
        case 2: return PARTICIPANT_TYPE_PEOPLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ParticipantTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ParticipantTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ParticipantTypeEnum>() {
            public ParticipantTypeEnum findValueByNumber(int number) {
              return ParticipantTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(11);
    }

    private static final ParticipantTypeEnum[] VALUES = values();

    public static ParticipantTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ParticipantTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ParticipantTypeEnum)
  }

  /**
   * <pre>
   * 应用状态
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.ApplicationStatusEnum}
   */
  public enum ApplicationStatusEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>APPLICATION_STATUS_UNKNOWN = 0;</code>
     */
    APPLICATION_STATUS_UNKNOWN(0),
    /**
     * <pre>
     * 已创建
     * </pre>
     *
     * <code>APPLICATION_STATUS_CREATED = 1;</code>
     */
    APPLICATION_STATUS_CREATED(1),
    /**
     * <pre>
     * 已审计
     * </pre>
     *
     * <code>APPLICATION_STATUS_AUDITED = 2;</code>
     */
    APPLICATION_STATUS_AUDITED(2),
    /**
     * <pre>
     * 已拒绝
     * </pre>
     *
     * <code>APPLICATION_STATUS_REFUSED = 3;</code>
     */
    APPLICATION_STATUS_REFUSED(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ApplicationStatusEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>APPLICATION_STATUS_UNKNOWN = 0;</code>
     */
    public static final int APPLICATION_STATUS_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 已创建
     * </pre>
     *
     * <code>APPLICATION_STATUS_CREATED = 1;</code>
     */
    public static final int APPLICATION_STATUS_CREATED_VALUE = 1;
    /**
     * <pre>
     * 已审计
     * </pre>
     *
     * <code>APPLICATION_STATUS_AUDITED = 2;</code>
     */
    public static final int APPLICATION_STATUS_AUDITED_VALUE = 2;
    /**
     * <pre>
     * 已拒绝
     * </pre>
     *
     * <code>APPLICATION_STATUS_REFUSED = 3;</code>
     */
    public static final int APPLICATION_STATUS_REFUSED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ApplicationStatusEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ApplicationStatusEnum forNumber(int value) {
      switch (value) {
        case 0: return APPLICATION_STATUS_UNKNOWN;
        case 1: return APPLICATION_STATUS_CREATED;
        case 2: return APPLICATION_STATUS_AUDITED;
        case 3: return APPLICATION_STATUS_REFUSED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ApplicationStatusEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ApplicationStatusEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ApplicationStatusEnum>() {
            public ApplicationStatusEnum findValueByNumber(int number) {
              return ApplicationStatusEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(12);
    }

    private static final ApplicationStatusEnum[] VALUES = values();

    public static ApplicationStatusEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ApplicationStatusEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.ApplicationStatusEnum)
  }

  /**
   * <pre>
   * 密码学类型
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.CipherTypeEnum}
   */
  public enum CipherTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>CIPHER_TYPE_UNKNOWN = 0;</code>
     */
    CIPHER_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * AES_GCM，加密算法
     * </pre>
     *
     * <code>CIPHER_TYPE_AES_GCM_256 = 1;</code>
     */
    CIPHER_TYPE_AES_GCM_256(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        CipherTypeEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>CIPHER_TYPE_UNKNOWN = 0;</code>
     */
    public static final int CIPHER_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * AES_GCM，加密算法
     * </pre>
     *
     * <code>CIPHER_TYPE_AES_GCM_256 = 1;</code>
     */
    public static final int CIPHER_TYPE_AES_GCM_256_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CipherTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CipherTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return CIPHER_TYPE_UNKNOWN;
        case 1: return CIPHER_TYPE_AES_GCM_256;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CipherTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CipherTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CipherTypeEnum>() {
            public CipherTypeEnum findValueByNumber(int number) {
              return CipherTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(13);
    }

    private static final CipherTypeEnum[] VALUES = values();

    public static CipherTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CipherTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.CipherTypeEnum)
  }

  /**
   * <pre>
   * 鉴权类型
   * </pre>
   *
   * Protobuf enum {@code yeying.api.common.AuthenticateTypeEnum}
   */
  public enum AuthenticateTypeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>AUTHENTICATE_TYPE_UNKNOWN = 0;</code>
     */
    AUTHENTICATE_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * 基于证书的认证
     * </pre>
     *
     * <code>AUTHENTICATE_TYPE_CERT = 1;</code>
     */
    AUTHENTICATE_TYPE_CERT(1),
    /**
     * <pre>
     * 基于token的认证
     * </pre>
     *
     * <code>AUTHENTICATE_TYPE_TOKEN = 2;</code>
     */
    AUTHENTICATE_TYPE_TOKEN(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        AuthenticateTypeEnum.class.getName());
    }
    /**
     * <pre>
     * 未知编码，是一种占位符
     * </pre>
     *
     * <code>AUTHENTICATE_TYPE_UNKNOWN = 0;</code>
     */
    public static final int AUTHENTICATE_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 基于证书的认证
     * </pre>
     *
     * <code>AUTHENTICATE_TYPE_CERT = 1;</code>
     */
    public static final int AUTHENTICATE_TYPE_CERT_VALUE = 1;
    /**
     * <pre>
     * 基于token的认证
     * </pre>
     *
     * <code>AUTHENTICATE_TYPE_TOKEN = 2;</code>
     */
    public static final int AUTHENTICATE_TYPE_TOKEN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AuthenticateTypeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AuthenticateTypeEnum forNumber(int value) {
      switch (value) {
        case 0: return AUTHENTICATE_TYPE_UNKNOWN;
        case 1: return AUTHENTICATE_TYPE_CERT;
        case 2: return AUTHENTICATE_TYPE_TOKEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthenticateTypeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthenticateTypeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthenticateTypeEnum>() {
            public AuthenticateTypeEnum findValueByNumber(int number) {
              return AuthenticateTypeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return yeying.api.common.Code.getDescriptor().getEnumTypes().get(14);
    }

    private static final AuthenticateTypeEnum[] VALUES = values();

    public static AuthenticateTypeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AuthenticateTypeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yeying.api.common.AuthenticateTypeEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034yeying/api/common/code.proto\022\021yeying.a" +
      "pi.common*\236\002\n\020ResponseCodeEnum\022\031\n\025RESPON" +
      "SE_CODE_UNKNOWN\020\000\022\006\n\002OK\020\001\022\024\n\020INVALID_ARG" +
      "UMENT\020\002\022\023\n\017UNAUTHENTICATED\020\003\022\025\n\021PERMISSI" +
      "ON_DENIED\020\004\022\r\n\tNOT_FOUND\020\005\022\022\n\016ALREADY_EX" +
      "ISTS\020\006\022\022\n\016LIMIT_EXCEEDED\020\007\022\017\n\013UNAVAILABL" +
      "E\020\010\022\021\n\rUNKNOWN_ERROR\020\t\022\021\n\rNETWORK_ERROR\020" +
      "\n\022\020\n\014INVALID_CERT\020\013\022\021\n\rNOT_SUPPORTED\020\014\022\022" +
      "\n\016DATA_CORRUPTED\020\r*\254\001\n\022ContractStatusEnu" +
      "m\022\033\n\027CONTRACT_STATUS_UNKNOWN\020\000\022\037\n\033CONTRA" +
      "CT_STATUS_INACTIVATED\020\001\022\035\n\031CONTRACT_STAT" +
      "US_ACTIVATED\020\002\022\033\n\027CONTRACT_STATUS_EXPIRE" +
      "D\020\003\022\034\n\030CONTRACT_STATUS_CANCELED\020\004*_\n\020Lan" +
      "guageCodeEnum\022\031\n\025LANGUAGE_CODE_UNKNOWN\020\000" +
      "\022\027\n\023LANGUAGE_CODE_ZH_CH\020\001\022\027\n\023LANGUAGE_CO" +
      "DE_EN_US\020\002*\346\001\n\023ApplicationCodeEnum\022\034\n\030AP" +
      "PLICATION_CODE_UNKNOWN\020\000\022\033\n\027APPLICATION_" +
      "CODE_MARKET\020\001\022\032\n\026APPLICATION_CODE_ASSET\020" +
      "\002\022\036\n\032APPLICATION_CODE_KNOWLEDGE\020\003\022\033\n\027APP" +
      "LICATION_CODE_KEEPER\020\004\022\033\n\027APPLICATION_CO" +
      "DE_SOCIAL\020\005\022\036\n\032APPLICATION_CODE_WORKBENC" +
      "H\020\006*\241\001\n\017ServiceCodeEnum\022\030\n\024SERVICE_CODE_" +
      "UNKNOWN\020\000\022\025\n\021SERVICE_CODE_NODE\020\001\022\032\n\026SERV" +
      "ICE_CODE_WAREHOUSE\020\002\022\026\n\022SERVICE_CODE_AGE" +
      "NT\020\003\022\024\n\020SERVICE_CODE_MCP\020\004\022\023\n\017SERVICE_CO" +
      "DE_AI\020\005*\230\003\n\013ApiCodeEnum\022\024\n\020API_CODE_UNKN" +
      "OWN\020\000\022\021\n\rAPI_CODE_USER\020\001\022\025\n\021API_CODE_IDE" +
      "NTITY\020\002\022\030\n\024API_CODE_LLM_SERVICE\020\003\022\031\n\025API" +
      "_CODE_LLM_PROVIDER\020\004\022\032\n\026API_CODE_ASSET_S" +
      "ERVICE\020\005\022\030\n\024API_CODE_ASSET_BLOCK\020\006\022\027\n\023AP" +
      "I_CODE_ASSET_LINK\020\007\022\034\n\030API_CODE_ASSET_NA" +
      "MESPACE\020\010\022\032\n\026API_CODE_ASSET_RECYCLE\020\t\022\030\n" +
      "\024API_CODE_CERTIFICATE\020\n\022\024\n\020API_CODE_STOR" +
      "AGE\020\013\022\030\n\024API_CODE_APPLICATION\020\014\022\022\n\016API_C" +
      "ODE_EVENT\020\r\022\027\n\023API_CODE_INVITATION\020\016\022\024\n\020" +
      "API_CODE_SERVICE\020\017*A\n\017ImageFormatEnum\022\030\n" +
      "\024IMAGE_FORMAT_UNKNOWN\020\000\022\024\n\020IMAGE_FORMAT_" +
      "PNG\020\001*\311\001\n\021DigitalFormatEnum\022\032\n\026DIGITAL_F" +
      "ORMAT_UNKNOWN\020\000\022\027\n\023DIGITAL_FORMAT_TEXT\020\001" +
      "\022\030\n\024DIGITAL_FORMAT_IMAGE\020\002\022\030\n\024DIGITAL_FO" +
      "RMAT_VIDEO\020\003\022\030\n\024DIGITAL_FORMAT_AUDIO\020\004\022\026" +
      "\n\022DIGITAL_FORMAT_APP\020\005\022\031\n\024DIGITAL_FORMAT" +
      "_OTHER\020\220N*b\n\021ContentFormatEnum\022\032\n\026CONTEN" +
      "T_FORMAT_UNKNOWN\020\000\022\026\n\022CONTENT_FORMAT_URL" +
      "\020\001\022\031\n\025CONTENT_FORMAT_BASE64\020\002*\203\001\n\020Sessio" +
      "nSceneEnum\022\031\n\025SESSION_SCENE_UNKNOWN\020\000\022\032\n" +
      "\026SESSION_SCENE_DIALOGUE\020\001\022\031\n\025SESSION_SCE" +
      "NE_DRAWING\020\002\022\035\n\031SESSION_SCENE_TRANSLATIO" +
      "N\020\003*a\n\017SessionRoleEnum\022\030\n\024SESSION_ROLE_U" +
      "NKNOWN\020\000\022\034\n\030SESSION_ROLE_PARTICIPANT\020\001\022\026" +
      "\n\022SESSION_ROLE_ADMIN\020\002*n\n\023ParticipantTyp" +
      "eEnum\022\034\n\030PARTICIPANT_TYPE_UNKNOWN\020\000\022\034\n\030P" +
      "ARTICIPANT_TYPE_SERVICE\020\001\022\033\n\027PARTICIPANT" +
      "_TYPE_PEOPLE\020\002*\227\001\n\025ApplicationStatusEnum" +
      "\022\036\n\032APPLICATION_STATUS_UNKNOWN\020\000\022\036\n\032APPL" +
      "ICATION_STATUS_CREATED\020\001\022\036\n\032APPLICATION_" +
      "STATUS_AUDITED\020\002\022\036\n\032APPLICATION_STATUS_R" +
      "EFUSED\020\003*F\n\016CipherTypeEnum\022\027\n\023CIPHER_TYP" +
      "E_UNKNOWN\020\000\022\033\n\027CIPHER_TYPE_AES_GCM_256\020\001" +
      "*n\n\024AuthenticateTypeEnum\022\035\n\031AUTHENTICATE" +
      "_TYPE_UNKNOWN\020\000\022\032\n\026AUTHENTICATE_TYPE_CER" +
      "T\020\001\022\033\n\027AUTHENTICATE_TYPE_TOKEN\020\002B\023Z\021yeyi" +
      "ng/api/commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
